// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.14.0
// source: runtime_launcher_interface.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RootfsSrcType int32

const (
	RootfsSrcType_S3    RootfsSrcType = 0
	RootfsSrcType_IMAGE RootfsSrcType = 1
	RootfsSrcType_LOCAL RootfsSrcType = 2
)

// Enum value maps for RootfsSrcType.
var (
	RootfsSrcType_name = map[int32]string{
		0: "S3",
		1: "IMAGE",
		2: "LOCAL",
	}
	RootfsSrcType_value = map[string]int32{
		"S3":    0,
		"IMAGE": 1,
		"LOCAL": 2,
	}
)

func (x RootfsSrcType) Enum() *RootfsSrcType {
	p := new(RootfsSrcType)
	*p = x
	return p
}

func (x RootfsSrcType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RootfsSrcType) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_launcher_interface_proto_enumTypes[0].Descriptor()
}

func (RootfsSrcType) Type() protoreflect.EnumType {
	return &file_runtime_launcher_interface_proto_enumTypes[0]
}

func (x RootfsSrcType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RootfsSrcType.Descriptor instead.
func (RootfsSrcType) EnumDescriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{0}
}

type ContainerState int32

const (
	ContainerState_CONTAINER_RUNNING ContainerState = 0
	ContainerState_CONTAINER_EXITED  ContainerState = 1
	ContainerState_CONTAINER_UNKNOWN ContainerState = 2
)

// Enum value maps for ContainerState.
var (
	ContainerState_name = map[int32]string{
		0: "CONTAINER_RUNNING",
		1: "CONTAINER_EXITED",
		2: "CONTAINER_UNKNOWN",
	}
	ContainerState_value = map[string]int32{
		"CONTAINER_RUNNING": 0,
		"CONTAINER_EXITED":  1,
		"CONTAINER_UNKNOWN": 2,
	}
)

func (x ContainerState) Enum() *ContainerState {
	p := new(ContainerState)
	*p = x
	return p
}

func (x ContainerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerState) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_launcher_interface_proto_enumTypes[1].Descriptor()
}

func (ContainerState) Type() protoreflect.EnumType {
	return &file_runtime_launcher_interface_proto_enumTypes[1]
}

func (x ContainerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerState.Descriptor instead.
func (ContainerState) EnumDescriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{1}
}

type S3Config struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Endpoint        string                 `protobuf:"bytes,1,opt,name=Endpoint,proto3" json:"Endpoint,omitempty"`
	Bucket          string                 `protobuf:"bytes,2,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Object          string                 `protobuf:"bytes,3,opt,name=Object,proto3" json:"Object,omitempty"`
	AccessKeyID     string                 `protobuf:"bytes,4,opt,name=AccessKeyID,proto3" json:"AccessKeyID,omitempty"`         // omitempty
	AccessKeySecret string                 `protobuf:"bytes,5,opt,name=AccessKeySecret,proto3" json:"AccessKeySecret,omitempty"` // omitempty
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *S3Config) Reset() {
	*x = S3Config{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Config) ProtoMessage() {}

func (x *S3Config) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Config.ProtoReflect.Descriptor instead.
func (*S3Config) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{0}
}

func (x *S3Config) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *S3Config) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *S3Config) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *S3Config) GetAccessKeyID() string {
	if x != nil {
		return x.AccessKeyID
	}
	return ""
}

func (x *S3Config) GetAccessKeySecret() string {
	if x != nil {
		return x.AccessKeySecret
	}
	return ""
}

type RootfsConfig struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Readonly bool                   `protobuf:"varint,1,opt,name=readonly,proto3" json:"readonly,omitempty"`
	Type     RootfsSrcType          `protobuf:"varint,2,opt,name=type,proto3,enum=runtime.v1.RootfsSrcType" json:"type,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*RootfsConfig_ImageUrl
	//	*RootfsConfig_S3Config
	//	*RootfsConfig_Path
	Source        isRootfsConfig_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootfsConfig) Reset() {
	*x = RootfsConfig{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootfsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootfsConfig) ProtoMessage() {}

func (x *RootfsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootfsConfig.ProtoReflect.Descriptor instead.
func (*RootfsConfig) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{1}
}

func (x *RootfsConfig) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

func (x *RootfsConfig) GetType() RootfsSrcType {
	if x != nil {
		return x.Type
	}
	return RootfsSrcType_S3
}

func (x *RootfsConfig) GetSource() isRootfsConfig_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *RootfsConfig) GetImageUrl() string {
	if x != nil {
		if x, ok := x.Source.(*RootfsConfig_ImageUrl); ok {
			return x.ImageUrl
		}
	}
	return ""
}

func (x *RootfsConfig) GetS3Config() *S3Config {
	if x != nil {
		if x, ok := x.Source.(*RootfsConfig_S3Config); ok {
			return x.S3Config
		}
	}
	return nil
}

func (x *RootfsConfig) GetPath() string {
	if x != nil {
		if x, ok := x.Source.(*RootfsConfig_Path); ok {
			return x.Path
		}
	}
	return ""
}

type isRootfsConfig_Source interface {
	isRootfsConfig_Source()
}

type RootfsConfig_ImageUrl struct {
	ImageUrl string `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3,oneof"`
}

type RootfsConfig_S3Config struct {
	S3Config *S3Config `protobuf:"bytes,4,opt,name=s3_config,json=s3Config,proto3,oneof"`
}

type RootfsConfig_Path struct {
	Path string `protobuf:"bytes,5,opt,name=path,proto3,oneof"`
}

func (*RootfsConfig_ImageUrl) isRootfsConfig_Source() {}

func (*RootfsConfig_S3Config) isRootfsConfig_Source() {}

func (*RootfsConfig_Path) isRootfsConfig_Source() {}

type Mount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type defines the nature of the mount (e.g. bind, volume, tmpfs).
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Target path in container.
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Options specifies zero or more fstab style mount options.
	Options []string `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*Mount_HostPath
	//	*Mount_S3Config
	//	*Mount_ImageUrl
	Source        isMount_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mount) Reset() {
	*x = Mount{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mount) ProtoMessage() {}

func (x *Mount) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mount.ProtoReflect.Descriptor instead.
func (*Mount) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{2}
}

func (x *Mount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Mount) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Mount) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Mount) GetSource() isMount_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Mount) GetHostPath() string {
	if x != nil {
		if x, ok := x.Source.(*Mount_HostPath); ok {
			return x.HostPath
		}
	}
	return ""
}

func (x *Mount) GetS3Config() *S3Config {
	if x != nil {
		if x, ok := x.Source.(*Mount_S3Config); ok {
			return x.S3Config
		}
	}
	return nil
}

func (x *Mount) GetImageUrl() string {
	if x != nil {
		if x, ok := x.Source.(*Mount_ImageUrl); ok {
			return x.ImageUrl
		}
	}
	return ""
}

type isMount_Source interface {
	isMount_Source()
}

type Mount_HostPath struct {
	// Host path (bind mount) or volume name.
	HostPath string `protobuf:"bytes,10,opt,name=host_path,json=hostPath,proto3,oneof"`
}

type Mount_S3Config struct {
	// S3-based mount source.
	S3Config *S3Config `protobuf:"bytes,11,opt,name=s3_config,json=s3Config,proto3,oneof"`
}

type Mount_ImageUrl struct {
	// OCI image URL for image-based mount.
	ImageUrl string `protobuf:"bytes,12,opt,name=image_url,json=imageUrl,proto3,oneof"`
}

func (*Mount_HostPath) isMount_Source() {}

func (*Mount_S3Config) isMount_Source() {}

func (*Mount_ImageUrl) isMount_Source() {}

type FunctionRuntime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sandbox       string                 `protobuf:"bytes,2,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	Rootfs        *RootfsConfig          `protobuf:"bytes,3,opt,name=rootfs,proto3" json:"rootfs,omitempty"`
	MakeSeed      bool                   `protobuf:"varint,4,opt,name=makeSeed,proto3" json:"makeSeed,omitempty"`
	Command       []string               `protobuf:"bytes,5,rep,name=command,proto3" json:"command,omitempty"`
	RuntimeEnvs   map[string]string      `protobuf:"bytes,6,rep,name=runtimeEnvs,proto3" json:"runtimeEnvs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cwd           string                 `protobuf:"bytes,7,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Mounts        []*Mount               `protobuf:"bytes,8,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionRuntime) Reset() {
	*x = FunctionRuntime{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionRuntime) ProtoMessage() {}

func (x *FunctionRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionRuntime.ProtoReflect.Descriptor instead.
func (*FunctionRuntime) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{3}
}

func (x *FunctionRuntime) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FunctionRuntime) GetSandbox() string {
	if x != nil {
		return x.Sandbox
	}
	return ""
}

func (x *FunctionRuntime) GetRootfs() *RootfsConfig {
	if x != nil {
		return x.Rootfs
	}
	return nil
}

func (x *FunctionRuntime) GetMakeSeed() bool {
	if x != nil {
		return x.MakeSeed
	}
	return false
}

func (x *FunctionRuntime) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *FunctionRuntime) GetRuntimeEnvs() map[string]string {
	if x != nil {
		return x.RuntimeEnvs
	}
	return nil
}

func (x *FunctionRuntime) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *FunctionRuntime) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type StartRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	FuncRuntime *FunctionRuntime       `protobuf:"bytes,1,opt,name=funcRuntime,proto3" json:"funcRuntime,omitempty"`
	Mounts      []*Mount               `protobuf:"bytes,2,rep,name=mounts,proto3" json:"mounts,omitempty"`
	// resource request of function
	// etc: CPU millicore​
	//
	//	Memory MB
	Resources map[string]float64 `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	UserEnvs  map[string]string  `protobuf:"bytes,4,rep,name=userEnvs,proto3" json:"userEnvs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// redirect path for stdout
	Stdout string `protobuf:"bytes,5,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// redirect path for stderr
	Stderr string `protobuf:"bytes,6,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// json string for customized config
	ExtraConfig string `protobuf:"bytes,7,opt,name=extraConfig,proto3" json:"extraConfig,omitempty"`
	// network indicates the type of network the function use,
	// default is sandbox, support: sandbox, host, none
	Network string `protobuf:"bytes,8,opt,name=network,proto3" json:"network,omitempty"`
	CkptDir string `protobuf:"bytes,9,opt,name=ckpt_dir,json=ckptDir,proto3" json:"ckpt_dir,omitempty"`
	TraceId string `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// port format: 'protocol:dstPort:targetPort'
	Ports         []string `protobuf:"bytes,11,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{4}
}

func (x *StartRequest) GetFuncRuntime() *FunctionRuntime {
	if x != nil {
		return x.FuncRuntime
	}
	return nil
}

func (x *StartRequest) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *StartRequest) GetResources() map[string]float64 {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *StartRequest) GetUserEnvs() map[string]string {
	if x != nil {
		return x.UserEnvs
	}
	return nil
}

func (x *StartRequest) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *StartRequest) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *StartRequest) GetExtraConfig() string {
	if x != nil {
		return x.ExtraConfig
	}
	return ""
}

func (x *StartRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *StartRequest) GetCkptDir() string {
	if x != nil {
		return x.CkptDir
	}
	return ""
}

func (x *StartRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *StartRequest) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

type StartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success:0
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// message indicating details about why start return with specific code
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// unique id of process/container
	Id            string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{5}
}

func (x *StartResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// timeout in seconds to wait for the process/container to graceful stop
	// before force delete
	Timeout       int64 `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{7}
}

type WaitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitRequest) Reset() {
	*x = WaitRequest{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitRequest) ProtoMessage() {}

func (x *WaitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitRequest.ProtoReflect.Descriptor instead.
func (*WaitRequest) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{8}
}

func (x *WaitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WaitResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// Exit code of the container. Only required when finished_at != 0. Default:
	// 0.
	ExitCode int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Human-readable message indicating details about why container is in its
	// current state.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitResponse) Reset() {
	*x = WaitResponse{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitResponse) ProtoMessage() {}

func (x *WaitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitResponse.ProtoReflect.Descriptor instead.
func (*WaitResponse) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{9}
}

func (x *WaitResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WaitResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *WaitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FuncRuntimes  []*FunctionRuntime     `protobuf:"bytes,1,rep,name=funcRuntimes,proto3" json:"funcRuntimes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterRequest) GetFuncRuntimes() []*FunctionRuntime {
	if x != nil {
		return x.FuncRuntimes
	}
	return nil
}

type NormalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalResponse) Reset() {
	*x = NormalResponse{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalResponse) ProtoMessage() {}

func (x *NormalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalResponse.ProtoReflect.Descriptor instead.
func (*NormalResponse) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{11}
}

func (x *NormalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NormalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{12}
}

func (x *UnregisterRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetRegisteredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegisteredRequest) Reset() {
	*x = GetRegisteredRequest{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegisteredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegisteredRequest) ProtoMessage() {}

func (x *GetRegisteredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegisteredRequest.ProtoReflect.Descriptor instead.
func (*GetRegisteredRequest) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{13}
}

type GetRegisteredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FuncRuntimes  []*FunctionRuntime     `protobuf:"bytes,1,rep,name=funcRuntimes,proto3" json:"funcRuntimes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegisteredResponse) Reset() {
	*x = GetRegisteredResponse{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegisteredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegisteredResponse) ProtoMessage() {}

func (x *GetRegisteredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegisteredResponse.ProtoReflect.Descriptor instead.
func (*GetRegisteredResponse) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{14}
}

func (x *GetRegisteredResponse) GetFuncRuntimes() []*FunctionRuntime {
	if x != nil {
		return x.FuncRuntimes
	}
	return nil
}

type CheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CkptDir       string                 `protobuf:"bytes,2,opt,name=ckpt_dir,json=ckptDir,proto3" json:"ckpt_dir,omitempty"`
	Timeout       int64                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Compress      bool                   `protobuf:"varint,4,opt,name=compress,proto3" json:"compress,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointRequest) Reset() {
	*x = CheckpointRequest{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointRequest) ProtoMessage() {}

func (x *CheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointRequest.ProtoReflect.Descriptor instead.
func (*CheckpointRequest) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{15}
}

func (x *CheckpointRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckpointRequest) GetCkptDir() string {
	if x != nil {
		return x.CkptDir
	}
	return ""
}

func (x *CheckpointRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *CheckpointRequest) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

func (x *CheckpointRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type CheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointResponse) Reset() {
	*x = CheckpointResponse{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResponse) ProtoMessage() {}

func (x *CheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResponse.ProtoReflect.Descriptor instead.
func (*CheckpointResponse) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{16}
}

func (x *CheckpointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckpointResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListContainersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the container.(equal to Get container xxx)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// selector to list containers with specified labels.(default to all)
	Selector      map[string]string `protobuf:"bytes,10,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersRequest) Reset() {
	*x = ListContainersRequest{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersRequest) ProtoMessage() {}

func (x *ListContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersRequest.ProtoReflect.Descriptor instead.
func (*ListContainersRequest) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{17}
}

func (x *ListContainersRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListContainersRequest) GetSelector() map[string]string {
	if x != nil {
		return x.Selector
	}
	return nil
}

type ListContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerStatus     `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersResponse) Reset() {
	*x = ListContainersResponse{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersResponse) ProtoMessage() {}

func (x *ListContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersResponse.ProtoReflect.Descriptor instead.
func (*ListContainersResponse) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{18}
}

func (x *ListContainersResponse) GetContainers() []*ContainerStatus {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ContainerStatus struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Command       []string                 `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Runtime       string                   `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	State         ContainerState           `protobuf:"varint,4,opt,name=state,proto3,enum=runtime.v1.ContainerState" json:"state,omitempty"`
	StartedAt     int64                    `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    int64                    `protobuf:"varint,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	ExitCode      int32                    `protobuf:"varint,7,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Message       string                   `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	Labels        map[string]string        `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Mounts        []*Mount                 `protobuf:"bytes,10,rep,name=mounts,proto3" json:"mounts,omitempty"`
	Envs          []*KeyValue              `protobuf:"bytes,11,rep,name=envs,proto3" json:"envs,omitempty"`
	Stdout        string                   `protobuf:"bytes,12,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                   `protobuf:"bytes,13,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Resources     *LinuxContainerResources `protobuf:"bytes,14,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStatus) Reset() {
	*x = ContainerStatus{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatus) ProtoMessage() {}

func (x *ContainerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatus.ProtoReflect.Descriptor instead.
func (*ContainerStatus) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{19}
}

func (x *ContainerStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerStatus) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ContainerStatus) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *ContainerStatus) GetState() ContainerState {
	if x != nil {
		return x.State
	}
	return ContainerState_CONTAINER_RUNNING
}

func (x *ContainerStatus) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *ContainerStatus) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *ContainerStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ContainerStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ContainerStatus) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ContainerStatus) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *ContainerStatus) GetEnvs() []*KeyValue {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *ContainerStatus) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ContainerStatus) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ContainerStatus) GetResources() *LinuxContainerResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{20}
}

func (x *VersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Runtimes      []*RuntimeVersion      `protobuf:"bytes,2,rep,name=runtimes,proto3" json:"runtimes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{21}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionResponse) GetRuntimes() []*RuntimeVersion {
	if x != nil {
		return x.Runtimes
	}
	return nil
}

type RuntimeVersion struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RuntimeName    string                 `protobuf:"bytes,1,opt,name=runtime_name,json=runtimeName,proto3" json:"runtime_name,omitempty"`
	RuntimeVersion string                 `protobuf:"bytes,2,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RuntimeVersion) Reset() {
	*x = RuntimeVersion{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeVersion) ProtoMessage() {}

func (x *RuntimeVersion) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeVersion.ProtoReflect.Descriptor instead.
func (*RuntimeVersion) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{22}
}

func (x *RuntimeVersion) GetRuntimeName() string {
	if x != nil {
		return x.RuntimeName
	}
	return ""
}

func (x *RuntimeVersion) GetRuntimeVersion() string {
	if x != nil {
		return x.RuntimeVersion
	}
	return ""
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{23}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LinuxContainerResources struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CpuPeriod              uint64                 `protobuf:"varint,1,opt,name=cpu_period,json=cpuPeriod,proto3" json:"cpu_period,omitempty"`
	CpuQuota               int64                  `protobuf:"varint,2,opt,name=cpu_quota,json=cpuQuota,proto3" json:"cpu_quota,omitempty"`
	CpuShares              uint64                 `protobuf:"varint,3,opt,name=cpu_shares,json=cpuShares,proto3" json:"cpu_shares,omitempty"`
	MemoryLimitInBytes     int64                  `protobuf:"varint,4,opt,name=memory_limit_in_bytes,json=memoryLimitInBytes,proto3" json:"memory_limit_in_bytes,omitempty"`
	OomScoreAdj            int64                  `protobuf:"varint,5,opt,name=oom_score_adj,json=oomScoreAdj,proto3" json:"oom_score_adj,omitempty"`
	CpusetCpus             string                 `protobuf:"bytes,6,opt,name=cpuset_cpus,json=cpusetCpus,proto3" json:"cpuset_cpus,omitempty"`
	CpusetMems             string                 `protobuf:"bytes,7,opt,name=cpuset_mems,json=cpusetMems,proto3" json:"cpuset_mems,omitempty"`
	HugepageLimits         []*HugepageLimit       `protobuf:"bytes,8,rep,name=hugepage_limits,json=hugepageLimits,proto3" json:"hugepage_limits,omitempty"`
	Unified                map[string]string      `protobuf:"bytes,9,rep,name=unified,proto3" json:"unified,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MemorySwapLimitInBytes int64                  `protobuf:"varint,10,opt,name=memory_swap_limit_in_bytes,json=memorySwapLimitInBytes,proto3" json:"memory_swap_limit_in_bytes,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LinuxContainerResources) Reset() {
	*x = LinuxContainerResources{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinuxContainerResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinuxContainerResources) ProtoMessage() {}

func (x *LinuxContainerResources) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinuxContainerResources.ProtoReflect.Descriptor instead.
func (*LinuxContainerResources) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{24}
}

func (x *LinuxContainerResources) GetCpuPeriod() uint64 {
	if x != nil {
		return x.CpuPeriod
	}
	return 0
}

func (x *LinuxContainerResources) GetCpuQuota() int64 {
	if x != nil {
		return x.CpuQuota
	}
	return 0
}

func (x *LinuxContainerResources) GetCpuShares() uint64 {
	if x != nil {
		return x.CpuShares
	}
	return 0
}

func (x *LinuxContainerResources) GetMemoryLimitInBytes() int64 {
	if x != nil {
		return x.MemoryLimitInBytes
	}
	return 0
}

func (x *LinuxContainerResources) GetOomScoreAdj() int64 {
	if x != nil {
		return x.OomScoreAdj
	}
	return 0
}

func (x *LinuxContainerResources) GetCpusetCpus() string {
	if x != nil {
		return x.CpusetCpus
	}
	return ""
}

func (x *LinuxContainerResources) GetCpusetMems() string {
	if x != nil {
		return x.CpusetMems
	}
	return ""
}

func (x *LinuxContainerResources) GetHugepageLimits() []*HugepageLimit {
	if x != nil {
		return x.HugepageLimits
	}
	return nil
}

func (x *LinuxContainerResources) GetUnified() map[string]string {
	if x != nil {
		return x.Unified
	}
	return nil
}

func (x *LinuxContainerResources) GetMemorySwapLimitInBytes() int64 {
	if x != nil {
		return x.MemorySwapLimitInBytes
	}
	return 0
}

type HugepageLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      string                 `protobuf:"bytes,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HugepageLimit) Reset() {
	*x = HugepageLimit{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HugepageLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HugepageLimit) ProtoMessage() {}

func (x *HugepageLimit) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HugepageLimit.ProtoReflect.Descriptor instead.
func (*HugepageLimit) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{25}
}

func (x *HugepageLimit) GetPageSize() string {
	if x != nil {
		return x.PageSize
	}
	return ""
}

func (x *HugepageLimit) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{26}
}

func (x *StatsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total CPU usage in nanoseconds.
	CpuUsageNs uint64 `protobuf:"varint,1,opt,name=cpu_usage_ns,json=cpuUsageNs,proto3" json:"cpu_usage_ns,omitempty"`
	// Current memory usage in bytes.
	MemoryUsageBytes uint64 `protobuf:"varint,2,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	// Memory limit in bytes.
	MemoryLimitBytes uint64 `protobuf:"varint,3,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	// Maximum memory usage observed in bytes.
	MemoryMaxUsageBytes uint64 `protobuf:"varint,4,opt,name=memory_max_usage_bytes,json=memoryMaxUsageBytes,proto3" json:"memory_max_usage_bytes,omitempty"`
	// CPU usage in kernel mode in nanoseconds.
	CpuKernelNs uint64 `protobuf:"varint,5,opt,name=cpu_kernel_ns,json=cpuKernelNs,proto3" json:"cpu_kernel_ns,omitempty"`
	// CPU usage in user mode in nanoseconds.
	CpuUserNs     uint64 `protobuf:"varint,6,opt,name=cpu_user_ns,json=cpuUserNs,proto3" json:"cpu_user_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_runtime_launcher_interface_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_launcher_interface_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_runtime_launcher_interface_proto_rawDescGZIP(), []int{27}
}

func (x *StatsResponse) GetCpuUsageNs() uint64 {
	if x != nil {
		return x.CpuUsageNs
	}
	return 0
}

func (x *StatsResponse) GetMemoryUsageBytes() uint64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *StatsResponse) GetMemoryLimitBytes() uint64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *StatsResponse) GetMemoryMaxUsageBytes() uint64 {
	if x != nil {
		return x.MemoryMaxUsageBytes
	}
	return 0
}

func (x *StatsResponse) GetCpuKernelNs() uint64 {
	if x != nil {
		return x.CpuKernelNs
	}
	return 0
}

func (x *StatsResponse) GetCpuUserNs() uint64 {
	if x != nil {
		return x.CpuUserNs
	}
	return 0
}

var File_runtime_launcher_interface_proto protoreflect.FileDescriptor

const file_runtime_launcher_interface_proto_rawDesc = "" +
	"\n" +
	" runtime_launcher_interface.proto\x12\n" +
	"runtime.v1\"\xa2\x01\n" +
	"\bS3Config\x12\x1a\n" +
	"\bEndpoint\x18\x01 \x01(\tR\bEndpoint\x12\x16\n" +
	"\x06Bucket\x18\x02 \x01(\tR\x06Bucket\x12\x16\n" +
	"\x06Object\x18\x03 \x01(\tR\x06Object\x12 \n" +
	"\vAccessKeyID\x18\x04 \x01(\tR\vAccessKeyID\x12(\n" +
	"\x0fAccessKeySecret\x18\x05 \x01(\tR\x0fAccessKeySecret\"\xcd\x01\n" +
	"\fRootfsConfig\x12\x1a\n" +
	"\breadonly\x18\x01 \x01(\bR\breadonly\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.runtime.v1.RootfsSrcTypeR\x04type\x12\x1d\n" +
	"\timage_url\x18\x03 \x01(\tH\x00R\bimageUrl\x123\n" +
	"\ts3_config\x18\x04 \x01(\v2\x14.runtime.v1.S3ConfigH\x00R\bs3Config\x12\x14\n" +
	"\x04path\x18\x05 \x01(\tH\x00R\x04pathB\b\n" +
	"\x06source\"\xca\x01\n" +
	"\x05Mount\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x12\x1d\n" +
	"\thost_path\x18\n" +
	" \x01(\tH\x00R\bhostPath\x123\n" +
	"\ts3_config\x18\v \x01(\v2\x14.runtime.v1.S3ConfigH\x00R\bs3Config\x12\x1d\n" +
	"\timage_url\x18\f \x01(\tH\x00R\bimageUrlB\b\n" +
	"\x06source\"\xf0\x02\n" +
	"\x0fFunctionRuntime\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asandbox\x18\x02 \x01(\tR\asandbox\x120\n" +
	"\x06rootfs\x18\x03 \x01(\v2\x18.runtime.v1.RootfsConfigR\x06rootfs\x12\x1a\n" +
	"\bmakeSeed\x18\x04 \x01(\bR\bmakeSeed\x12\x18\n" +
	"\acommand\x18\x05 \x03(\tR\acommand\x12N\n" +
	"\vruntimeEnvs\x18\x06 \x03(\v2,.runtime.v1.FunctionRuntime.RuntimeEnvsEntryR\vruntimeEnvs\x12\x10\n" +
	"\x03cwd\x18\a \x01(\tR\x03cwd\x12)\n" +
	"\x06mounts\x18\b \x03(\v2\x11.runtime.v1.MountR\x06mounts\x1a>\n" +
	"\x10RuntimeEnvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x04\n" +
	"\fStartRequest\x12=\n" +
	"\vfuncRuntime\x18\x01 \x01(\v2\x1b.runtime.v1.FunctionRuntimeR\vfuncRuntime\x12)\n" +
	"\x06mounts\x18\x02 \x03(\v2\x11.runtime.v1.MountR\x06mounts\x12E\n" +
	"\tresources\x18\x03 \x03(\v2'.runtime.v1.StartRequest.ResourcesEntryR\tresources\x12B\n" +
	"\buserEnvs\x18\x04 \x03(\v2&.runtime.v1.StartRequest.UserEnvsEntryR\buserEnvs\x12\x16\n" +
	"\x06stdout\x18\x05 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x06 \x01(\tR\x06stderr\x12 \n" +
	"\vextraConfig\x18\a \x01(\tR\vextraConfig\x12\x18\n" +
	"\anetwork\x18\b \x01(\tR\anetwork\x12\x19\n" +
	"\bckpt_dir\x18\t \x01(\tR\ackptDir\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\x12\x14\n" +
	"\x05ports\x18\v \x03(\tR\x05ports\x1a<\n" +
	"\x0eResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a;\n" +
	"\rUserEnvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\rStartResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"9\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x03R\atimeout\"\x10\n" +
	"\x0eDeleteResponse\"\x1d\n" +
	"\vWaitRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"]\n" +
	"\fWaitResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"R\n" +
	"\x0fRegisterRequest\x12?\n" +
	"\ffuncRuntimes\x18\x01 \x03(\v2\x1b.runtime.v1.FunctionRuntimeR\ffuncRuntimes\"D\n" +
	"\x0eNormalResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\x11UnregisterRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\x16\n" +
	"\x14GetRegisteredRequest\"X\n" +
	"\x15GetRegisteredResponse\x12?\n" +
	"\ffuncRuntimes\x18\x01 \x03(\v2\x1b.runtime.v1.FunctionRuntimeR\ffuncRuntimes\"\x8f\x01\n" +
	"\x11CheckpointRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bckpt_dir\x18\x02 \x01(\tR\ackptDir\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x03R\atimeout\x12\x1a\n" +
	"\bcompress\x18\x04 \x01(\bR\bcompress\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\"H\n" +
	"\x12CheckpointResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb1\x01\n" +
	"\x15ListContainersRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12K\n" +
	"\bselector\x18\n" +
	" \x03(\v2/.runtime.v1.ListContainersRequest.SelectorEntryR\bselector\x1a;\n" +
	"\rSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\x16ListContainersResponse\x12;\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x1b.runtime.v1.ContainerStatusR\n" +
	"containers\"\xc2\x04\n" +
	"\x0fContainerStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x18\n" +
	"\aruntime\x18\x03 \x01(\tR\aruntime\x120\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1a.runtime.v1.ContainerStateR\x05state\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x06 \x01(\x03R\n" +
	"finishedAt\x12\x1b\n" +
	"\texit_code\x18\a \x01(\x05R\bexitCode\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x12?\n" +
	"\x06labels\x18\t \x03(\v2'.runtime.v1.ContainerStatus.LabelsEntryR\x06labels\x12)\n" +
	"\x06mounts\x18\n" +
	" \x03(\v2\x11.runtime.v1.MountR\x06mounts\x12(\n" +
	"\x04envs\x18\v \x03(\v2\x14.runtime.v1.KeyValueR\x04envs\x12\x16\n" +
	"\x06stdout\x18\f \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\r \x01(\tR\x06stderr\x12A\n" +
	"\tresources\x18\x0e \x01(\v2#.runtime.v1.LinuxContainerResourcesR\tresources\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\x0eVersionRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"c\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x126\n" +
	"\bruntimes\x18\x02 \x03(\v2\x1a.runtime.v1.RuntimeVersionR\bruntimes\"\\\n" +
	"\x0eRuntimeVersion\x12!\n" +
	"\fruntime_name\x18\x01 \x01(\tR\vruntimeName\x12'\n" +
	"\x0fruntime_version\x18\x02 \x01(\tR\x0eruntimeVersion\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x95\x04\n" +
	"\x17LinuxContainerResources\x12\x1d\n" +
	"\n" +
	"cpu_period\x18\x01 \x01(\x04R\tcpuPeriod\x12\x1b\n" +
	"\tcpu_quota\x18\x02 \x01(\x03R\bcpuQuota\x12\x1d\n" +
	"\n" +
	"cpu_shares\x18\x03 \x01(\x04R\tcpuShares\x121\n" +
	"\x15memory_limit_in_bytes\x18\x04 \x01(\x03R\x12memoryLimitInBytes\x12\"\n" +
	"\room_score_adj\x18\x05 \x01(\x03R\voomScoreAdj\x12\x1f\n" +
	"\vcpuset_cpus\x18\x06 \x01(\tR\n" +
	"cpusetCpus\x12\x1f\n" +
	"\vcpuset_mems\x18\a \x01(\tR\n" +
	"cpusetMems\x12B\n" +
	"\x0fhugepage_limits\x18\b \x03(\v2\x19.runtime.v1.HugepageLimitR\x0ehugepageLimits\x12J\n" +
	"\aunified\x18\t \x03(\v20.runtime.v1.LinuxContainerResources.UnifiedEntryR\aunified\x12:\n" +
	"\x1amemory_swap_limit_in_bytes\x18\n" +
	" \x01(\x03R\x16memorySwapLimitInBytes\x1a:\n" +
	"\fUnifiedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\rHugepageLimit\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\tR\bpageSize\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\"\x1e\n" +
	"\fStatsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x86\x02\n" +
	"\rStatsResponse\x12 \n" +
	"\fcpu_usage_ns\x18\x01 \x01(\x04R\n" +
	"cpuUsageNs\x12,\n" +
	"\x12memory_usage_bytes\x18\x02 \x01(\x04R\x10memoryUsageBytes\x12,\n" +
	"\x12memory_limit_bytes\x18\x03 \x01(\x04R\x10memoryLimitBytes\x123\n" +
	"\x16memory_max_usage_bytes\x18\x04 \x01(\x04R\x13memoryMaxUsageBytes\x12\"\n" +
	"\rcpu_kernel_ns\x18\x05 \x01(\x04R\vcpuKernelNs\x12\x1e\n" +
	"\vcpu_user_ns\x18\x06 \x01(\x04R\tcpuUserNs*-\n" +
	"\rRootfsSrcType\x12\x06\n" +
	"\x02S3\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01\x12\t\n" +
	"\x05LOCAL\x10\x02*T\n" +
	"\x0eContainerState\x12\x15\n" +
	"\x11CONTAINER_RUNNING\x10\x00\x12\x14\n" +
	"\x10CONTAINER_EXITED\x10\x01\x12\x15\n" +
	"\x11CONTAINER_UNKNOWN\x10\x022\xe1\x05\n" +
	"\x0fRuntimeLauncher\x12>\n" +
	"\x05Start\x12\x18.runtime.v1.StartRequest\x1a\x19.runtime.v1.StartResponse\"\x00\x12A\n" +
	"\x06Delete\x12\x19.runtime.v1.DeleteRequest\x1a\x1a.runtime.v1.DeleteResponse\"\x00\x12;\n" +
	"\x04Wait\x12\x17.runtime.v1.WaitRequest\x1a\x18.runtime.v1.WaitResponse\"\x00\x12E\n" +
	"\bRegister\x12\x1b.runtime.v1.RegisterRequest\x1a\x1a.runtime.v1.NormalResponse\"\x00\x12I\n" +
	"\n" +
	"Unregister\x12\x1d.runtime.v1.UnregisterRequest\x1a\x1a.runtime.v1.NormalResponse\"\x00\x12V\n" +
	"\rGetRegistered\x12 .runtime.v1.GetRegisteredRequest\x1a!.runtime.v1.GetRegisteredResponse\"\x00\x12M\n" +
	"\n" +
	"Checkpoint\x12\x1d.runtime.v1.CheckpointRequest\x1a\x1e.runtime.v1.CheckpointResponse\"\x00\x12O\n" +
	"\x04List\x12!.runtime.v1.ListContainersRequest\x1a\".runtime.v1.ListContainersResponse\"\x00\x12>\n" +
	"\x05Stats\x12\x18.runtime.v1.StatsRequest\x1a\x19.runtime.v1.StatsResponse\"\x00\x12D\n" +
	"\aVersion\x12\x1a.runtime.v1.VersionRequest\x1a\x1b.runtime.v1.VersionResponse\"\x00b\x06proto3"

var (
	file_runtime_launcher_interface_proto_rawDescOnce sync.Once
	file_runtime_launcher_interface_proto_rawDescData []byte
)

func file_runtime_launcher_interface_proto_rawDescGZIP() []byte {
	file_runtime_launcher_interface_proto_rawDescOnce.Do(func() {
		file_runtime_launcher_interface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_launcher_interface_proto_rawDesc), len(file_runtime_launcher_interface_proto_rawDesc)))
	})
	return file_runtime_launcher_interface_proto_rawDescData
}

var file_runtime_launcher_interface_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_runtime_launcher_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_runtime_launcher_interface_proto_goTypes = []any{
	(RootfsSrcType)(0),              // 0: runtime.v1.RootfsSrcType
	(ContainerState)(0),             // 1: runtime.v1.ContainerState
	(*S3Config)(nil),                // 2: runtime.v1.S3Config
	(*RootfsConfig)(nil),            // 3: runtime.v1.RootfsConfig
	(*Mount)(nil),                   // 4: runtime.v1.Mount
	(*FunctionRuntime)(nil),         // 5: runtime.v1.FunctionRuntime
	(*StartRequest)(nil),            // 6: runtime.v1.StartRequest
	(*StartResponse)(nil),           // 7: runtime.v1.StartResponse
	(*DeleteRequest)(nil),           // 8: runtime.v1.DeleteRequest
	(*DeleteResponse)(nil),          // 9: runtime.v1.DeleteResponse
	(*WaitRequest)(nil),             // 10: runtime.v1.WaitRequest
	(*WaitResponse)(nil),            // 11: runtime.v1.WaitResponse
	(*RegisterRequest)(nil),         // 12: runtime.v1.RegisterRequest
	(*NormalResponse)(nil),          // 13: runtime.v1.NormalResponse
	(*UnregisterRequest)(nil),       // 14: runtime.v1.UnregisterRequest
	(*GetRegisteredRequest)(nil),    // 15: runtime.v1.GetRegisteredRequest
	(*GetRegisteredResponse)(nil),   // 16: runtime.v1.GetRegisteredResponse
	(*CheckpointRequest)(nil),       // 17: runtime.v1.CheckpointRequest
	(*CheckpointResponse)(nil),      // 18: runtime.v1.CheckpointResponse
	(*ListContainersRequest)(nil),   // 19: runtime.v1.ListContainersRequest
	(*ListContainersResponse)(nil),  // 20: runtime.v1.ListContainersResponse
	(*ContainerStatus)(nil),         // 21: runtime.v1.ContainerStatus
	(*VersionRequest)(nil),          // 22: runtime.v1.VersionRequest
	(*VersionResponse)(nil),         // 23: runtime.v1.VersionResponse
	(*RuntimeVersion)(nil),          // 24: runtime.v1.RuntimeVersion
	(*KeyValue)(nil),                // 25: runtime.v1.KeyValue
	(*LinuxContainerResources)(nil), // 26: runtime.v1.LinuxContainerResources
	(*HugepageLimit)(nil),           // 27: runtime.v1.HugepageLimit
	(*StatsRequest)(nil),            // 28: runtime.v1.StatsRequest
	(*StatsResponse)(nil),           // 29: runtime.v1.StatsResponse
	nil,                             // 30: runtime.v1.FunctionRuntime.RuntimeEnvsEntry
	nil,                             // 31: runtime.v1.StartRequest.ResourcesEntry
	nil,                             // 32: runtime.v1.StartRequest.UserEnvsEntry
	nil,                             // 33: runtime.v1.ListContainersRequest.SelectorEntry
	nil,                             // 34: runtime.v1.ContainerStatus.LabelsEntry
	nil,                             // 35: runtime.v1.LinuxContainerResources.UnifiedEntry
}
var file_runtime_launcher_interface_proto_depIdxs = []int32{
	0,  // 0: runtime.v1.RootfsConfig.type:type_name -> runtime.v1.RootfsSrcType
	2,  // 1: runtime.v1.RootfsConfig.s3_config:type_name -> runtime.v1.S3Config
	2,  // 2: runtime.v1.Mount.s3_config:type_name -> runtime.v1.S3Config
	3,  // 3: runtime.v1.FunctionRuntime.rootfs:type_name -> runtime.v1.RootfsConfig
	30, // 4: runtime.v1.FunctionRuntime.runtimeEnvs:type_name -> runtime.v1.FunctionRuntime.RuntimeEnvsEntry
	4,  // 5: runtime.v1.FunctionRuntime.mounts:type_name -> runtime.v1.Mount
	5,  // 6: runtime.v1.StartRequest.funcRuntime:type_name -> runtime.v1.FunctionRuntime
	4,  // 7: runtime.v1.StartRequest.mounts:type_name -> runtime.v1.Mount
	31, // 8: runtime.v1.StartRequest.resources:type_name -> runtime.v1.StartRequest.ResourcesEntry
	32, // 9: runtime.v1.StartRequest.userEnvs:type_name -> runtime.v1.StartRequest.UserEnvsEntry
	5,  // 10: runtime.v1.RegisterRequest.funcRuntimes:type_name -> runtime.v1.FunctionRuntime
	5,  // 11: runtime.v1.GetRegisteredResponse.funcRuntimes:type_name -> runtime.v1.FunctionRuntime
	33, // 12: runtime.v1.ListContainersRequest.selector:type_name -> runtime.v1.ListContainersRequest.SelectorEntry
	21, // 13: runtime.v1.ListContainersResponse.containers:type_name -> runtime.v1.ContainerStatus
	1,  // 14: runtime.v1.ContainerStatus.state:type_name -> runtime.v1.ContainerState
	34, // 15: runtime.v1.ContainerStatus.labels:type_name -> runtime.v1.ContainerStatus.LabelsEntry
	4,  // 16: runtime.v1.ContainerStatus.mounts:type_name -> runtime.v1.Mount
	25, // 17: runtime.v1.ContainerStatus.envs:type_name -> runtime.v1.KeyValue
	26, // 18: runtime.v1.ContainerStatus.resources:type_name -> runtime.v1.LinuxContainerResources
	24, // 19: runtime.v1.VersionResponse.runtimes:type_name -> runtime.v1.RuntimeVersion
	27, // 20: runtime.v1.LinuxContainerResources.hugepage_limits:type_name -> runtime.v1.HugepageLimit
	35, // 21: runtime.v1.LinuxContainerResources.unified:type_name -> runtime.v1.LinuxContainerResources.UnifiedEntry
	6,  // 22: runtime.v1.RuntimeLauncher.Start:input_type -> runtime.v1.StartRequest
	8,  // 23: runtime.v1.RuntimeLauncher.Delete:input_type -> runtime.v1.DeleteRequest
	10, // 24: runtime.v1.RuntimeLauncher.Wait:input_type -> runtime.v1.WaitRequest
	12, // 25: runtime.v1.RuntimeLauncher.Register:input_type -> runtime.v1.RegisterRequest
	14, // 26: runtime.v1.RuntimeLauncher.Unregister:input_type -> runtime.v1.UnregisterRequest
	15, // 27: runtime.v1.RuntimeLauncher.GetRegistered:input_type -> runtime.v1.GetRegisteredRequest
	17, // 28: runtime.v1.RuntimeLauncher.Checkpoint:input_type -> runtime.v1.CheckpointRequest
	19, // 29: runtime.v1.RuntimeLauncher.List:input_type -> runtime.v1.ListContainersRequest
	28, // 30: runtime.v1.RuntimeLauncher.Stats:input_type -> runtime.v1.StatsRequest
	22, // 31: runtime.v1.RuntimeLauncher.Version:input_type -> runtime.v1.VersionRequest
	7,  // 32: runtime.v1.RuntimeLauncher.Start:output_type -> runtime.v1.StartResponse
	9,  // 33: runtime.v1.RuntimeLauncher.Delete:output_type -> runtime.v1.DeleteResponse
	11, // 34: runtime.v1.RuntimeLauncher.Wait:output_type -> runtime.v1.WaitResponse
	13, // 35: runtime.v1.RuntimeLauncher.Register:output_type -> runtime.v1.NormalResponse
	13, // 36: runtime.v1.RuntimeLauncher.Unregister:output_type -> runtime.v1.NormalResponse
	16, // 37: runtime.v1.RuntimeLauncher.GetRegistered:output_type -> runtime.v1.GetRegisteredResponse
	18, // 38: runtime.v1.RuntimeLauncher.Checkpoint:output_type -> runtime.v1.CheckpointResponse
	20, // 39: runtime.v1.RuntimeLauncher.List:output_type -> runtime.v1.ListContainersResponse
	29, // 40: runtime.v1.RuntimeLauncher.Stats:output_type -> runtime.v1.StatsResponse
	23, // 41: runtime.v1.RuntimeLauncher.Version:output_type -> runtime.v1.VersionResponse
	32, // [32:42] is the sub-list for method output_type
	22, // [22:32] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_runtime_launcher_interface_proto_init() }
func file_runtime_launcher_interface_proto_init() {
	if File_runtime_launcher_interface_proto != nil {
		return
	}
	file_runtime_launcher_interface_proto_msgTypes[1].OneofWrappers = []any{
		(*RootfsConfig_ImageUrl)(nil),
		(*RootfsConfig_S3Config)(nil),
		(*RootfsConfig_Path)(nil),
	}
	file_runtime_launcher_interface_proto_msgTypes[2].OneofWrappers = []any{
		(*Mount_HostPath)(nil),
		(*Mount_S3Config)(nil),
		(*Mount_ImageUrl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_launcher_interface_proto_rawDesc), len(file_runtime_launcher_interface_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_launcher_interface_proto_goTypes,
		DependencyIndexes: file_runtime_launcher_interface_proto_depIdxs,
		EnumInfos:         file_runtime_launcher_interface_proto_enumTypes,
		MessageInfos:      file_runtime_launcher_interface_proto_msgTypes,
	}.Build()
	File_runtime_launcher_interface_proto = out.File
	file_runtime_launcher_interface_proto_goTypes = nil
	file_runtime_launcher_interface_proto_depIdxs = nil
}
