// Copyright (c) 2026 Huawei Technologies Co., Ltd. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.14.0
// source: sandbox_api.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RootfsSrcType identifies the root filesystem source type.
type RootfsSrcType int32

const (
	RootfsSrcType_S3    RootfsSrcType = 0
	RootfsSrcType_IMAGE RootfsSrcType = 1
	RootfsSrcType_LOCAL RootfsSrcType = 2
)

// Enum value maps for RootfsSrcType.
var (
	RootfsSrcType_name = map[int32]string{
		0: "S3",
		1: "IMAGE",
		2: "LOCAL",
	}
	RootfsSrcType_value = map[string]int32{
		"S3":    0,
		"IMAGE": 1,
		"LOCAL": 2,
	}
)

func (x RootfsSrcType) Enum() *RootfsSrcType {
	p := new(RootfsSrcType)
	*p = x
	return p
}

func (x RootfsSrcType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RootfsSrcType) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_api_proto_enumTypes[0].Descriptor()
}

func (RootfsSrcType) Type() protoreflect.EnumType {
	return &file_sandbox_api_proto_enumTypes[0]
}

func (x RootfsSrcType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RootfsSrcType.Descriptor instead.
func (RootfsSrcType) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{0}
}

// SandboxState is the persisted lifecycle state of a sandbox.
type SandboxState int32

const (
	SandboxState_SANDBOX_STATE_RUNNING SandboxState = 0
	SandboxState_SANDBOX_STATE_EXITED  SandboxState = 1
	SandboxState_SANDBOX_STATE_UNKNOWN SandboxState = 2
)

// Enum value maps for SandboxState.
var (
	SandboxState_name = map[int32]string{
		0: "SANDBOX_STATE_RUNNING",
		1: "SANDBOX_STATE_EXITED",
		2: "SANDBOX_STATE_UNKNOWN",
	}
	SandboxState_value = map[string]int32{
		"SANDBOX_STATE_RUNNING": 0,
		"SANDBOX_STATE_EXITED":  1,
		"SANDBOX_STATE_UNKNOWN": 2,
	}
)

func (x SandboxState) Enum() *SandboxState {
	p := new(SandboxState)
	*p = x
	return p
}

func (x SandboxState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxState) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_api_proto_enumTypes[1].Descriptor()
}

func (SandboxState) Type() protoreflect.EnumType {
	return &file_sandbox_api_proto_enumTypes[1]
}

func (x SandboxState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandboxState.Descriptor instead.
func (SandboxState) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{1}
}

// S3Config describes an S3 object source.
type S3Config struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Endpoint        string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Bucket          string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Object          string                 `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	AccessKeyId     string                 `protobuf:"bytes,4,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	AccessKeySecret string                 `protobuf:"bytes,5,opt,name=access_key_secret,json=accessKeySecret,proto3" json:"access_key_secret,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *S3Config) Reset() {
	*x = S3Config{}
	mi := &file_sandbox_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Config) ProtoMessage() {}

func (x *S3Config) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Config.ProtoReflect.Descriptor instead.
func (*S3Config) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{0}
}

func (x *S3Config) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *S3Config) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *S3Config) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *S3Config) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *S3Config) GetAccessKeySecret() string {
	if x != nil {
		return x.AccessKeySecret
	}
	return ""
}

// RootfsConfig describes the sandbox root filesystem source.
type RootfsConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Readonly makes the root filesystem read-only when true.
	Readonly bool `protobuf:"varint,1,opt,name=readonly,proto3" json:"readonly,omitempty"`
	// Type identifies the root filesystem source type.
	Type RootfsSrcType `protobuf:"varint,2,opt,name=type,proto3,enum=runtime.v1.RootfsSrcType" json:"type,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*RootfsConfig_ImageUrl
	//	*RootfsConfig_S3Config
	//	*RootfsConfig_Path
	Source        isRootfsConfig_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootfsConfig) Reset() {
	*x = RootfsConfig{}
	mi := &file_sandbox_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootfsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootfsConfig) ProtoMessage() {}

func (x *RootfsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootfsConfig.ProtoReflect.Descriptor instead.
func (*RootfsConfig) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{1}
}

func (x *RootfsConfig) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

func (x *RootfsConfig) GetType() RootfsSrcType {
	if x != nil {
		return x.Type
	}
	return RootfsSrcType_S3
}

func (x *RootfsConfig) GetSource() isRootfsConfig_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *RootfsConfig) GetImageUrl() string {
	if x != nil {
		if x, ok := x.Source.(*RootfsConfig_ImageUrl); ok {
			return x.ImageUrl
		}
	}
	return ""
}

func (x *RootfsConfig) GetS3Config() *S3Config {
	if x != nil {
		if x, ok := x.Source.(*RootfsConfig_S3Config); ok {
			return x.S3Config
		}
	}
	return nil
}

func (x *RootfsConfig) GetPath() string {
	if x != nil {
		if x, ok := x.Source.(*RootfsConfig_Path); ok {
			return x.Path
		}
	}
	return ""
}

type isRootfsConfig_Source interface {
	isRootfsConfig_Source()
}

type RootfsConfig_ImageUrl struct {
	// ImageURL is the image URL used as the root filesystem source.
	ImageUrl string `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3,oneof"`
}

type RootfsConfig_S3Config struct {
	// S3Config is the S3 object used as the root filesystem source.
	S3Config *S3Config `protobuf:"bytes,4,opt,name=s3_config,json=s3Config,proto3,oneof"`
}

type RootfsConfig_Path struct {
	// Path is a local directory or file used as the root filesystem source.
	Path string `protobuf:"bytes,5,opt,name=path,proto3,oneof"`
}

func (*RootfsConfig_ImageUrl) isRootfsConfig_Source() {}

func (*RootfsConfig_S3Config) isRootfsConfig_Source() {}

func (*RootfsConfig_Path) isRootfsConfig_Source() {}

// Mount describes an additional mount attached to the sandbox.
type Mount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type identifies the mount type, such as bind, volume, or tmpfs.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Target is the mount target path inside the sandbox.
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Options contains zero or more fstab-style mount options.
	Options []string `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*Mount_HostPath
	//	*Mount_S3Config
	//	*Mount_ImageUrl
	Source        isMount_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mount) Reset() {
	*x = Mount{}
	mi := &file_sandbox_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mount) ProtoMessage() {}

func (x *Mount) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mount.ProtoReflect.Descriptor instead.
func (*Mount) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{2}
}

func (x *Mount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Mount) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Mount) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Mount) GetSource() isMount_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Mount) GetHostPath() string {
	if x != nil {
		if x, ok := x.Source.(*Mount_HostPath); ok {
			return x.HostPath
		}
	}
	return ""
}

func (x *Mount) GetS3Config() *S3Config {
	if x != nil {
		if x, ok := x.Source.(*Mount_S3Config); ok {
			return x.S3Config
		}
	}
	return nil
}

func (x *Mount) GetImageUrl() string {
	if x != nil {
		if x, ok := x.Source.(*Mount_ImageUrl); ok {
			return x.ImageUrl
		}
	}
	return ""
}

type isMount_Source interface {
	isMount_Source()
}

type Mount_HostPath struct {
	// HostPath is a host path for bind mounts or a volume name.
	HostPath string `protobuf:"bytes,10,opt,name=host_path,json=hostPath,proto3,oneof"`
}

type Mount_S3Config struct {
	// S3Config is the S3 object used as the mount source.
	S3Config *S3Config `protobuf:"bytes,11,opt,name=s3_config,json=s3Config,proto3,oneof"`
}

type Mount_ImageUrl struct {
	// ImageURL is the OCI image URL used as the mount source.
	ImageUrl string `protobuf:"bytes,12,opt,name=image_url,json=imageUrl,proto3,oneof"`
}

func (*Mount_HostPath) isMount_Source() {}

func (*Mount_S3Config) isMount_Source() {}

func (*Mount_ImageUrl) isMount_Source() {}

// StartRequest describes a sandbox start request.
type StartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SandboxID is an optional caller-provided sandbox ID. sandboxd generates one when empty.
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// TemplateID is the registered SandboxTemplate ID to start from. Only requests
	// with this field set are eligible to reuse a registered seed/fork path.
	TemplateId string `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// Runtime is the runtime handler name, such as runsc.
	Runtime string `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// Rootfs is the root filesystem source used by the sandbox.
	Rootfs *RootfsConfig `protobuf:"bytes,4,opt,name=rootfs,proto3" json:"rootfs,omitempty"`
	// Command is the executable and arguments to run inside the sandbox.
	Command []string `protobuf:"bytes,5,rep,name=command,proto3" json:"command,omitempty"`
	// Cwd is the working directory inside the sandbox.
	Cwd string `protobuf:"bytes,6,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Envs contains environment variables for the sandbox process.
	Envs map[string]string `protobuf:"bytes,7,rep,name=envs,proto3" json:"envs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Mounts contains additional mounts attached to the sandbox.
	Mounts []*Mount `protobuf:"bytes,8,rep,name=mounts,proto3" json:"mounts,omitempty"`
	// Resources contains sandbox resource requests. CPU is millicores and memory is MB.
	Resources map[string]float64 `protobuf:"bytes,9,rep,name=resources,proto3" json:"resources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	// Stdout is the redirect path for stdout. Empty means stdout is discarded to /dev/null.
	Stdout string `protobuf:"bytes,10,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// Stderr is the redirect path for stderr. Empty means stderr is discarded to /dev/null.
	Stderr string `protobuf:"bytes,11,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// ExtraConfig is a JSON string for runtime-specific configuration.
	ExtraConfig string `protobuf:"bytes,12,opt,name=extra_config,json=extraConfig,proto3" json:"extra_config,omitempty"`
	// Network is the network mode. Empty means sandbox network; supported values are sandbox, host, and none.
	Network string `protobuf:"bytes,13,opt,name=network,proto3" json:"network,omitempty"`
	// TraceID is an optional distributed trace ID.
	TraceId string `protobuf:"bytes,14,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Ports contains port forwarding entries in "protocol:dstPort:targetPort" format.
	Ports []string `protobuf:"bytes,15,rep,name=ports,proto3" json:"ports,omitempty"`
	// Labels contains sandbox labels used for selection and runtime metadata.
	Labels map[string]string `protobuf:"bytes,16,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// MetricLabels contains sandbox metadata intended for metric dimensions.
	MetricLabels  map[string]string `protobuf:"bytes,17,rep,name=metric_labels,json=metricLabels,proto3" json:"metric_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_sandbox_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{3}
}

func (x *StartRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *StartRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *StartRequest) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *StartRequest) GetRootfs() *RootfsConfig {
	if x != nil {
		return x.Rootfs
	}
	return nil
}

func (x *StartRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *StartRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *StartRequest) GetEnvs() map[string]string {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *StartRequest) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *StartRequest) GetResources() map[string]float64 {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *StartRequest) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *StartRequest) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *StartRequest) GetExtraConfig() string {
	if x != nil {
		return x.ExtraConfig
	}
	return ""
}

func (x *StartRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *StartRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *StartRequest) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *StartRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *StartRequest) GetMetricLabels() map[string]string {
	if x != nil {
		return x.MetricLabels
	}
	return nil
}

// StartResponse is returned after sandbox start.
type StartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Code is 0 on success.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Message contains details about the start result.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// ID is the unique sandbox ID.
	Id            string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_sandbox_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{4}
}

func (x *StartResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// RestoreRequest describes a sandbox restore request.
type RestoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sandbox contains the sandbox spec to create from a checkpoint.
	Sandbox *StartRequest `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	// CheckpointDir is the directory containing checkpoint artifacts.
	CheckpointDir string `protobuf:"bytes,2,opt,name=checkpoint_dir,json=checkpointDir,proto3" json:"checkpoint_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_sandbox_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{5}
}

func (x *RestoreRequest) GetSandbox() *StartRequest {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *RestoreRequest) GetCheckpointDir() string {
	if x != nil {
		return x.CheckpointDir
	}
	return ""
}

// RestoreResponse is returned after sandbox restore.
type RestoreResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Code is 0 on success.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Message contains details about the restore result.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// ID is the unique sandbox ID.
	Id            string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_sandbox_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{6}
}

func (x *RestoreResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RestoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RestoreResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteRequest describes a sandbox delete request.
type DeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the sandbox ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Timeout is the number of seconds to wait for graceful stop before force delete.
	Timeout       int64 `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_sandbox_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// DeleteResponse is returned after sandbox delete.
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_sandbox_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{8}
}

// WaitRequest describes a sandbox wait request.
type WaitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the sandbox ID.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitRequest) Reset() {
	*x = WaitRequest{}
	mi := &file_sandbox_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitRequest) ProtoMessage() {}

func (x *WaitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitRequest.ProtoReflect.Descriptor instead.
func (*WaitRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{9}
}

func (x *WaitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// WaitResponse is returned after waiting for a sandbox.
type WaitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status is the sandbox wait status.
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// Exit code of the sandbox. Only required when finished_at != 0. Default: 0.
	ExitCode int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Message contains details about the sandbox state.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitResponse) Reset() {
	*x = WaitResponse{}
	mi := &file_sandbox_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitResponse) ProtoMessage() {}

func (x *WaitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitResponse.ProtoReflect.Descriptor instead.
func (*WaitResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{10}
}

func (x *WaitResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WaitResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *WaitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SandboxTemplate describes a reusable sandbox template registered in sandboxd.
type SandboxTemplate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the registered template ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Runtime is the runtime handler name, such as runsc.
	Runtime string `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// Rootfs is the root filesystem source used by the template.
	Rootfs *RootfsConfig `protobuf:"bytes,3,opt,name=rootfs,proto3" json:"rootfs,omitempty"`
	// MakeSeed asks sandboxd to pre-create a seed sandbox when supported.
	MakeSeed bool `protobuf:"varint,4,opt,name=make_seed,json=makeSeed,proto3" json:"make_seed,omitempty"`
	// Command is the executable and arguments to run inside the sandbox.
	Command []string `protobuf:"bytes,5,rep,name=command,proto3" json:"command,omitempty"`
	// Envs contains environment variables for the sandbox process.
	Envs map[string]string `protobuf:"bytes,6,rep,name=envs,proto3" json:"envs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Cwd is the working directory inside the sandbox.
	Cwd string `protobuf:"bytes,7,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Mounts contains additional mounts attached to the sandbox.
	Mounts        []*Mount `protobuf:"bytes,8,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxTemplate) Reset() {
	*x = SandboxTemplate{}
	mi := &file_sandbox_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxTemplate) ProtoMessage() {}

func (x *SandboxTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxTemplate.ProtoReflect.Descriptor instead.
func (*SandboxTemplate) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{11}
}

func (x *SandboxTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SandboxTemplate) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *SandboxTemplate) GetRootfs() *RootfsConfig {
	if x != nil {
		return x.Rootfs
	}
	return nil
}

func (x *SandboxTemplate) GetMakeSeed() bool {
	if x != nil {
		return x.MakeSeed
	}
	return false
}

func (x *SandboxTemplate) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *SandboxTemplate) GetEnvs() map[string]string {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *SandboxTemplate) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *SandboxTemplate) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

// RegisterRequest describes sandbox template registration.
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Templates contains sandbox templates to register.
	Templates     []*SandboxTemplate `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_sandbox_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterRequest) GetTemplates() []*SandboxTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

// NormalResponse is returned by template registration operations.
type NormalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalResponse) Reset() {
	*x = NormalResponse{}
	mi := &file_sandbox_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalResponse) ProtoMessage() {}

func (x *NormalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalResponse.ProtoReflect.Descriptor instead.
func (*NormalResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{13}
}

func (x *NormalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NormalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UnregisterRequest describes sandbox template removal.
type UnregisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IDs contains sandbox template IDs to unregister.
	Ids           []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_sandbox_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{14}
}

func (x *UnregisterRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// GetRegisteredRequest describes a registered sandbox template list request.
type GetRegisteredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegisteredRequest) Reset() {
	*x = GetRegisteredRequest{}
	mi := &file_sandbox_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegisteredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegisteredRequest) ProtoMessage() {}

func (x *GetRegisteredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegisteredRequest.ProtoReflect.Descriptor instead.
func (*GetRegisteredRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{15}
}

// GetRegisteredResponse contains registered sandbox templates.
type GetRegisteredResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Templates contains registered sandbox templates.
	Templates     []*SandboxTemplate `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegisteredResponse) Reset() {
	*x = GetRegisteredResponse{}
	mi := &file_sandbox_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegisteredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegisteredResponse) ProtoMessage() {}

func (x *GetRegisteredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegisteredResponse.ProtoReflect.Descriptor instead.
func (*GetRegisteredResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{16}
}

func (x *GetRegisteredResponse) GetTemplates() []*SandboxTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

// CheckpointRequest describes a sandbox checkpoint request.
type CheckpointRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the sandbox ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// CheckpointDir is the output directory for checkpoint artifacts.
	CheckpointDir string `protobuf:"bytes,2,opt,name=checkpoint_dir,json=checkpointDir,proto3" json:"checkpoint_dir,omitempty"`
	// Timeout is the number of seconds to wait for checkpoint completion.
	Timeout int64 `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Compress enables checkpoint artifact compression when true.
	Compress bool `protobuf:"varint,4,opt,name=compress,proto3" json:"compress,omitempty"`
	// TraceID is an optional distributed trace ID.
	TraceId       string `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointRequest) Reset() {
	*x = CheckpointRequest{}
	mi := &file_sandbox_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointRequest) ProtoMessage() {}

func (x *CheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointRequest.ProtoReflect.Descriptor instead.
func (*CheckpointRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{17}
}

func (x *CheckpointRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckpointRequest) GetCheckpointDir() string {
	if x != nil {
		return x.CheckpointDir
	}
	return ""
}

func (x *CheckpointRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *CheckpointRequest) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

func (x *CheckpointRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// CheckpointResponse is returned after sandbox checkpoint.
type CheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointResponse) Reset() {
	*x = CheckpointResponse{}
	mi := &file_sandbox_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResponse) ProtoMessage() {}

func (x *CheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResponse.ProtoReflect.Descriptor instead.
func (*CheckpointResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{18}
}

func (x *CheckpointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckpointResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListSandboxesRequest describes a sandbox list request.
type ListSandboxesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID filters by sandbox ID when set.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Selector filters sandboxes by labels. Empty selector lists all sandboxes.
	Selector      map[string]string `protobuf:"bytes,10,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesRequest) Reset() {
	*x = ListSandboxesRequest{}
	mi := &file_sandbox_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesRequest) ProtoMessage() {}

func (x *ListSandboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesRequest.ProtoReflect.Descriptor instead.
func (*ListSandboxesRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{19}
}

func (x *ListSandboxesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListSandboxesRequest) GetSelector() map[string]string {
	if x != nil {
		return x.Selector
	}
	return nil
}

// ListSandboxesResponse contains sandbox list results.
type ListSandboxesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sandboxes contains matching sandbox statuses.
	Sandboxes     []*SandboxStatus `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesResponse) Reset() {
	*x = ListSandboxesResponse{}
	mi := &file_sandbox_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesResponse) ProtoMessage() {}

func (x *ListSandboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesResponse.ProtoReflect.Descriptor instead.
func (*ListSandboxesResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{20}
}

func (x *ListSandboxesResponse) GetSandboxes() []*SandboxStatus {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

// SandboxStatus describes the current status and metadata of a sandbox.
type SandboxStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the sandbox ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Command is the executable and arguments configured for the sandbox.
	Command []string `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	// Runtime is the runtime handler name.
	Runtime string `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// State is the current sandbox lifecycle state.
	State SandboxState `protobuf:"varint,4,opt,name=state,proto3,enum=runtime.v1.SandboxState" json:"state,omitempty"`
	// StartedAt is the sandbox start timestamp in Unix seconds.
	StartedAt int64 `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// FinishedAt is the sandbox finish timestamp in Unix seconds.
	FinishedAt int64 `protobuf:"varint,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	// ExitCode is the sandbox process exit code when available.
	ExitCode int32 `protobuf:"varint,7,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Message contains details about the sandbox state.
	Message string `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	// Labels contains sandbox labels.
	Labels map[string]string `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Mounts contains additional mounts attached to the sandbox.
	Mounts []*Mount `protobuf:"bytes,10,rep,name=mounts,proto3" json:"mounts,omitempty"`
	// Envs contains environment variables configured for the sandbox.
	Envs []*KeyValue `protobuf:"bytes,11,rep,name=envs,proto3" json:"envs,omitempty"`
	// Stdout is the configured stdout redirect path.
	Stdout string `protobuf:"bytes,12,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// Stderr is the configured stderr redirect path.
	Stderr string `protobuf:"bytes,13,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// Resources contains Linux resource settings for the sandbox.
	Resources *LinuxSandboxResources `protobuf:"bytes,14,opt,name=resources,proto3" json:"resources,omitempty"`
	// MetricLabels contains sandbox metadata intended for metric dimensions.
	MetricLabels  map[string]string `protobuf:"bytes,15,rep,name=metric_labels,json=metricLabels,proto3" json:"metric_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxStatus) Reset() {
	*x = SandboxStatus{}
	mi := &file_sandbox_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxStatus) ProtoMessage() {}

func (x *SandboxStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxStatus.ProtoReflect.Descriptor instead.
func (*SandboxStatus) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{21}
}

func (x *SandboxStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SandboxStatus) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *SandboxStatus) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *SandboxStatus) GetState() SandboxState {
	if x != nil {
		return x.State
	}
	return SandboxState_SANDBOX_STATE_RUNNING
}

func (x *SandboxStatus) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *SandboxStatus) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *SandboxStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *SandboxStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SandboxStatus) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SandboxStatus) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *SandboxStatus) GetEnvs() []*KeyValue {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *SandboxStatus) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *SandboxStatus) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *SandboxStatus) GetResources() *LinuxSandboxResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *SandboxStatus) GetMetricLabels() map[string]string {
	if x != nil {
		return x.MetricLabels
	}
	return nil
}

// KeyValue represents a string key-value pair.
type KeyValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key is the entry key.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Value is the entry value.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_sandbox_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{22}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// LinuxSandboxResources describes Linux resource settings for a sandbox.
type LinuxSandboxResources struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CPUPeriod is the CPU CFS period in microseconds.
	CpuPeriod uint64 `protobuf:"varint,1,opt,name=cpu_period,json=cpuPeriod,proto3" json:"cpu_period,omitempty"`
	// CPUQuota is the CPU CFS quota in microseconds.
	CpuQuota int64 `protobuf:"varint,2,opt,name=cpu_quota,json=cpuQuota,proto3" json:"cpu_quota,omitempty"`
	// CPUShares is the relative CPU share weight.
	CpuShares uint64 `protobuf:"varint,3,opt,name=cpu_shares,json=cpuShares,proto3" json:"cpu_shares,omitempty"`
	// MemoryLimitInBytes is the memory limit in bytes.
	MemoryLimitInBytes int64 `protobuf:"varint,4,opt,name=memory_limit_in_bytes,json=memoryLimitInBytes,proto3" json:"memory_limit_in_bytes,omitempty"`
	// OomScoreAdj is the OOM score adjustment.
	OomScoreAdj int64 `protobuf:"varint,5,opt,name=oom_score_adj,json=oomScoreAdj,proto3" json:"oom_score_adj,omitempty"`
	// CpusetCpus is the allowed CPU set.
	CpusetCpus string `protobuf:"bytes,6,opt,name=cpuset_cpus,json=cpusetCpus,proto3" json:"cpuset_cpus,omitempty"`
	// CpusetMems is the allowed memory node set.
	CpusetMems string `protobuf:"bytes,7,opt,name=cpuset_mems,json=cpusetMems,proto3" json:"cpuset_mems,omitempty"`
	// HugepageLimits contains hugepage limits by page size.
	HugepageLimits []*HugepageLimit `protobuf:"bytes,8,rep,name=hugepage_limits,json=hugepageLimits,proto3" json:"hugepage_limits,omitempty"`
	// Unified contains cgroup v2 unified controller settings.
	Unified map[string]string `protobuf:"bytes,9,rep,name=unified,proto3" json:"unified,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// MemorySwapLimitInBytes is the memory plus swap limit in bytes.
	MemorySwapLimitInBytes int64 `protobuf:"varint,10,opt,name=memory_swap_limit_in_bytes,json=memorySwapLimitInBytes,proto3" json:"memory_swap_limit_in_bytes,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LinuxSandboxResources) Reset() {
	*x = LinuxSandboxResources{}
	mi := &file_sandbox_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinuxSandboxResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinuxSandboxResources) ProtoMessage() {}

func (x *LinuxSandboxResources) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinuxSandboxResources.ProtoReflect.Descriptor instead.
func (*LinuxSandboxResources) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{23}
}

func (x *LinuxSandboxResources) GetCpuPeriod() uint64 {
	if x != nil {
		return x.CpuPeriod
	}
	return 0
}

func (x *LinuxSandboxResources) GetCpuQuota() int64 {
	if x != nil {
		return x.CpuQuota
	}
	return 0
}

func (x *LinuxSandboxResources) GetCpuShares() uint64 {
	if x != nil {
		return x.CpuShares
	}
	return 0
}

func (x *LinuxSandboxResources) GetMemoryLimitInBytes() int64 {
	if x != nil {
		return x.MemoryLimitInBytes
	}
	return 0
}

func (x *LinuxSandboxResources) GetOomScoreAdj() int64 {
	if x != nil {
		return x.OomScoreAdj
	}
	return 0
}

func (x *LinuxSandboxResources) GetCpusetCpus() string {
	if x != nil {
		return x.CpusetCpus
	}
	return ""
}

func (x *LinuxSandboxResources) GetCpusetMems() string {
	if x != nil {
		return x.CpusetMems
	}
	return ""
}

func (x *LinuxSandboxResources) GetHugepageLimits() []*HugepageLimit {
	if x != nil {
		return x.HugepageLimits
	}
	return nil
}

func (x *LinuxSandboxResources) GetUnified() map[string]string {
	if x != nil {
		return x.Unified
	}
	return nil
}

func (x *LinuxSandboxResources) GetMemorySwapLimitInBytes() int64 {
	if x != nil {
		return x.MemorySwapLimitInBytes
	}
	return 0
}

// HugepageLimit describes a hugepage limit for one page size.
type HugepageLimit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PageSize is the hugepage size.
	PageSize string `protobuf:"bytes,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Limit is the hugepage limit in bytes.
	Limit         uint64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HugepageLimit) Reset() {
	*x = HugepageLimit{}
	mi := &file_sandbox_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HugepageLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HugepageLimit) ProtoMessage() {}

func (x *HugepageLimit) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HugepageLimit.ProtoReflect.Descriptor instead.
func (*HugepageLimit) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{24}
}

func (x *HugepageLimit) GetPageSize() string {
	if x != nil {
		return x.PageSize
	}
	return ""
}

func (x *HugepageLimit) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SandboxMetadata contains the persisted metadata for a sandbox.
type SandboxMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the sandbox ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// RuntimeHandler is the runtime handler name.
	RuntimeHandler string `protobuf:"bytes,3,opt,name=runtime_handler,json=runtimeHandler,proto3" json:"runtime_handler,omitempty"`
	// Labels contains sandbox labels.
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Stdout is the configured stdout redirect path.
	Stdout string `protobuf:"bytes,6,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// Stderr is the configured stderr redirect path.
	Stderr string `protobuf:"bytes,7,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// MetricLabels contains sandbox metadata intended for metric dimensions.
	MetricLabels  map[string]string `protobuf:"bytes,8,rep,name=metric_labels,json=metricLabels,proto3" json:"metric_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxMetadata) Reset() {
	*x = SandboxMetadata{}
	mi := &file_sandbox_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxMetadata) ProtoMessage() {}

func (x *SandboxMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxMetadata.ProtoReflect.Descriptor instead.
func (*SandboxMetadata) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{25}
}

func (x *SandboxMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SandboxMetadata) GetRuntimeHandler() string {
	if x != nil {
		return x.RuntimeHandler
	}
	return ""
}

func (x *SandboxMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SandboxMetadata) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *SandboxMetadata) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *SandboxMetadata) GetMetricLabels() map[string]string {
	if x != nil {
		return x.MetricLabels
	}
	return nil
}

// SandboxMetadataList contains persisted sandbox metadata entries.
type SandboxMetadataList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sandboxes maps sandbox ID to sandbox metadata.
	Sandboxes     map[string]*SandboxMetadata `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxMetadataList) Reset() {
	*x = SandboxMetadataList{}
	mi := &file_sandbox_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxMetadataList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxMetadataList) ProtoMessage() {}

func (x *SandboxMetadataList) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxMetadataList.ProtoReflect.Descriptor instead.
func (*SandboxMetadataList) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{26}
}

func (x *SandboxMetadataList) GetSandboxes() map[string]*SandboxMetadata {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

// StatsRequest describes a sandbox stats request.
type StatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the sandbox ID.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_sandbox_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{27}
}

func (x *StatsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// StatsResponse contains sandbox resource usage statistics.
type StatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total CPU usage in nanoseconds.
	CpuUsageNs uint64 `protobuf:"varint,1,opt,name=cpu_usage_ns,json=cpuUsageNs,proto3" json:"cpu_usage_ns,omitempty"`
	// Current memory usage in bytes.
	MemoryUsageBytes uint64 `protobuf:"varint,2,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	// Memory limit in bytes.
	MemoryLimitBytes uint64 `protobuf:"varint,3,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	// Maximum memory usage observed in bytes.
	MemoryMaxUsageBytes uint64 `protobuf:"varint,4,opt,name=memory_max_usage_bytes,json=memoryMaxUsageBytes,proto3" json:"memory_max_usage_bytes,omitempty"`
	// CPU usage in kernel mode in nanoseconds.
	CpuKernelNs uint64 `protobuf:"varint,5,opt,name=cpu_kernel_ns,json=cpuKernelNs,proto3" json:"cpu_kernel_ns,omitempty"`
	// CPU usage in user mode in nanoseconds.
	CpuUserNs     uint64 `protobuf:"varint,6,opt,name=cpu_user_ns,json=cpuUserNs,proto3" json:"cpu_user_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_sandbox_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{28}
}

func (x *StatsResponse) GetCpuUsageNs() uint64 {
	if x != nil {
		return x.CpuUsageNs
	}
	return 0
}

func (x *StatsResponse) GetMemoryUsageBytes() uint64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *StatsResponse) GetMemoryLimitBytes() uint64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *StatsResponse) GetMemoryMaxUsageBytes() uint64 {
	if x != nil {
		return x.MemoryMaxUsageBytes
	}
	return 0
}

func (x *StatsResponse) GetCpuKernelNs() uint64 {
	if x != nil {
		return x.CpuKernelNs
	}
	return 0
}

func (x *StatsResponse) GetCpuUserNs() uint64 {
	if x != nil {
		return x.CpuUserNs
	}
	return 0
}

var File_sandbox_api_proto protoreflect.FileDescriptor

const file_sandbox_api_proto_rawDesc = "" +
	"\n" +
	"\x11sandbox_api.proto\x12\n" +
	"runtime.v1\"\xa6\x01\n" +
	"\bS3Config\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06object\x18\x03 \x01(\tR\x06object\x12\"\n" +
	"\raccess_key_id\x18\x04 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11access_key_secret\x18\x05 \x01(\tR\x0faccessKeySecret\"\xcd\x01\n" +
	"\fRootfsConfig\x12\x1a\n" +
	"\breadonly\x18\x01 \x01(\bR\breadonly\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.runtime.v1.RootfsSrcTypeR\x04type\x12\x1d\n" +
	"\timage_url\x18\x03 \x01(\tH\x00R\bimageUrl\x123\n" +
	"\ts3_config\x18\x04 \x01(\v2\x14.runtime.v1.S3ConfigH\x00R\bs3Config\x12\x14\n" +
	"\x04path\x18\x05 \x01(\tH\x00R\x04pathB\b\n" +
	"\x06source\"\xca\x01\n" +
	"\x05Mount\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x12\x1d\n" +
	"\thost_path\x18\n" +
	" \x01(\tH\x00R\bhostPath\x123\n" +
	"\ts3_config\x18\v \x01(\v2\x14.runtime.v1.S3ConfigH\x00R\bs3Config\x12\x1d\n" +
	"\timage_url\x18\f \x01(\tH\x00R\bimageUrlB\b\n" +
	"\x06source\"\x90\a\n" +
	"\fStartRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x18\n" +
	"\aruntime\x18\x03 \x01(\tR\aruntime\x120\n" +
	"\x06rootfs\x18\x04 \x01(\v2\x18.runtime.v1.RootfsConfigR\x06rootfs\x12\x18\n" +
	"\acommand\x18\x05 \x03(\tR\acommand\x12\x10\n" +
	"\x03cwd\x18\x06 \x01(\tR\x03cwd\x126\n" +
	"\x04envs\x18\a \x03(\v2\".runtime.v1.StartRequest.EnvsEntryR\x04envs\x12)\n" +
	"\x06mounts\x18\b \x03(\v2\x11.runtime.v1.MountR\x06mounts\x12E\n" +
	"\tresources\x18\t \x03(\v2'.runtime.v1.StartRequest.ResourcesEntryR\tresources\x12\x16\n" +
	"\x06stdout\x18\n" +
	" \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\v \x01(\tR\x06stderr\x12!\n" +
	"\fextra_config\x18\f \x01(\tR\vextraConfig\x12\x18\n" +
	"\anetwork\x18\r \x01(\tR\anetwork\x12\x19\n" +
	"\btrace_id\x18\x0e \x01(\tR\atraceId\x12\x14\n" +
	"\x05ports\x18\x0f \x03(\tR\x05ports\x12<\n" +
	"\x06labels\x18\x10 \x03(\v2$.runtime.v1.StartRequest.LabelsEntryR\x06labels\x12O\n" +
	"\rmetric_labels\x18\x11 \x03(\v2*.runtime.v1.StartRequest.MetricLabelsEntryR\fmetricLabels\x1a7\n" +
	"\tEnvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11MetricLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\rStartResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"k\n" +
	"\x0eRestoreRequest\x122\n" +
	"\asandbox\x18\x01 \x01(\v2\x18.runtime.v1.StartRequestR\asandbox\x12%\n" +
	"\x0echeckpoint_dir\x18\x02 \x01(\tR\rcheckpointDir\"O\n" +
	"\x0fRestoreResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"9\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x03R\atimeout\"\x10\n" +
	"\x0eDeleteResponse\"\x1d\n" +
	"\vWaitRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"]\n" +
	"\fWaitResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xd5\x02\n" +
	"\x0fSandboxTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aruntime\x18\x02 \x01(\tR\aruntime\x120\n" +
	"\x06rootfs\x18\x03 \x01(\v2\x18.runtime.v1.RootfsConfigR\x06rootfs\x12\x1b\n" +
	"\tmake_seed\x18\x04 \x01(\bR\bmakeSeed\x12\x18\n" +
	"\acommand\x18\x05 \x03(\tR\acommand\x129\n" +
	"\x04envs\x18\x06 \x03(\v2%.runtime.v1.SandboxTemplate.EnvsEntryR\x04envs\x12\x10\n" +
	"\x03cwd\x18\a \x01(\tR\x03cwd\x12)\n" +
	"\x06mounts\x18\b \x03(\v2\x11.runtime.v1.MountR\x06mounts\x1a7\n" +
	"\tEnvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x0fRegisterRequest\x129\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1b.runtime.v1.SandboxTemplateR\ttemplates\"D\n" +
	"\x0eNormalResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\x11UnregisterRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\x16\n" +
	"\x14GetRegisteredRequest\"R\n" +
	"\x15GetRegisteredResponse\x129\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1b.runtime.v1.SandboxTemplateR\ttemplates\"\x9b\x01\n" +
	"\x11CheckpointRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0echeckpoint_dir\x18\x02 \x01(\tR\rcheckpointDir\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x03R\atimeout\x12\x1a\n" +
	"\bcompress\x18\x04 \x01(\bR\bcompress\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\"H\n" +
	"\x12CheckpointResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xaf\x01\n" +
	"\x14ListSandboxesRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12J\n" +
	"\bselector\x18\n" +
	" \x03(\v2..runtime.v1.ListSandboxesRequest.SelectorEntryR\bselector\x1a;\n" +
	"\rSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x15ListSandboxesResponse\x127\n" +
	"\tsandboxes\x18\x01 \x03(\v2\x19.runtime.v1.SandboxStatusR\tsandboxes\"\xcd\x05\n" +
	"\rSandboxStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x18\n" +
	"\aruntime\x18\x03 \x01(\tR\aruntime\x12.\n" +
	"\x05state\x18\x04 \x01(\x0e2\x18.runtime.v1.SandboxStateR\x05state\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x06 \x01(\x03R\n" +
	"finishedAt\x12\x1b\n" +
	"\texit_code\x18\a \x01(\x05R\bexitCode\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x12=\n" +
	"\x06labels\x18\t \x03(\v2%.runtime.v1.SandboxStatus.LabelsEntryR\x06labels\x12)\n" +
	"\x06mounts\x18\n" +
	" \x03(\v2\x11.runtime.v1.MountR\x06mounts\x12(\n" +
	"\x04envs\x18\v \x03(\v2\x14.runtime.v1.KeyValueR\x04envs\x12\x16\n" +
	"\x06stdout\x18\f \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\r \x01(\tR\x06stderr\x12?\n" +
	"\tresources\x18\x0e \x01(\v2!.runtime.v1.LinuxSandboxResourcesR\tresources\x12P\n" +
	"\rmetric_labels\x18\x0f \x03(\v2+.runtime.v1.SandboxStatus.MetricLabelsEntryR\fmetricLabels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11MetricLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x91\x04\n" +
	"\x15LinuxSandboxResources\x12\x1d\n" +
	"\n" +
	"cpu_period\x18\x01 \x01(\x04R\tcpuPeriod\x12\x1b\n" +
	"\tcpu_quota\x18\x02 \x01(\x03R\bcpuQuota\x12\x1d\n" +
	"\n" +
	"cpu_shares\x18\x03 \x01(\x04R\tcpuShares\x121\n" +
	"\x15memory_limit_in_bytes\x18\x04 \x01(\x03R\x12memoryLimitInBytes\x12\"\n" +
	"\room_score_adj\x18\x05 \x01(\x03R\voomScoreAdj\x12\x1f\n" +
	"\vcpuset_cpus\x18\x06 \x01(\tR\n" +
	"cpusetCpus\x12\x1f\n" +
	"\vcpuset_mems\x18\a \x01(\tR\n" +
	"cpusetMems\x12B\n" +
	"\x0fhugepage_limits\x18\b \x03(\v2\x19.runtime.v1.HugepageLimitR\x0ehugepageLimits\x12H\n" +
	"\aunified\x18\t \x03(\v2..runtime.v1.LinuxSandboxResources.UnifiedEntryR\aunified\x12:\n" +
	"\x1amemory_swap_limit_in_bytes\x18\n" +
	" \x01(\x03R\x16memorySwapLimitInBytes\x1a:\n" +
	"\fUnifiedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\rHugepageLimit\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\tR\bpageSize\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\"\x8b\x03\n" +
	"\x0fSandboxMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fruntime_handler\x18\x03 \x01(\tR\x0eruntimeHandler\x12?\n" +
	"\x06labels\x18\x04 \x03(\v2'.runtime.v1.SandboxMetadata.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06stdout\x18\x06 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\a \x01(\tR\x06stderr\x12R\n" +
	"\rmetric_labels\x18\b \x03(\v2-.runtime.v1.SandboxMetadata.MetricLabelsEntryR\fmetricLabels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11MetricLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbe\x01\n" +
	"\x13SandboxMetadataList\x12L\n" +
	"\tsandboxes\x18\x01 \x03(\v2..runtime.v1.SandboxMetadataList.SandboxesEntryR\tsandboxes\x1aY\n" +
	"\x0eSandboxesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.runtime.v1.SandboxMetadataR\x05value:\x028\x01\"\x1e\n" +
	"\fStatsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x86\x02\n" +
	"\rStatsResponse\x12 \n" +
	"\fcpu_usage_ns\x18\x01 \x01(\x04R\n" +
	"cpuUsageNs\x12,\n" +
	"\x12memory_usage_bytes\x18\x02 \x01(\x04R\x10memoryUsageBytes\x12,\n" +
	"\x12memory_limit_bytes\x18\x03 \x01(\x04R\x10memoryLimitBytes\x123\n" +
	"\x16memory_max_usage_bytes\x18\x04 \x01(\x04R\x13memoryMaxUsageBytes\x12\"\n" +
	"\rcpu_kernel_ns\x18\x05 \x01(\x04R\vcpuKernelNs\x12\x1e\n" +
	"\vcpu_user_ns\x18\x06 \x01(\x04R\tcpuUserNs*-\n" +
	"\rRootfsSrcType\x12\x06\n" +
	"\x02S3\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01\x12\t\n" +
	"\x05LOCAL\x10\x02*^\n" +
	"\fSandboxState\x12\x19\n" +
	"\x15SANDBOX_STATE_RUNNING\x10\x00\x12\x18\n" +
	"\x14SANDBOX_STATE_EXITED\x10\x01\x12\x19\n" +
	"\x15SANDBOX_STATE_UNKNOWN\x10\x022\xde\x05\n" +
	"\x0eSandboxService\x12>\n" +
	"\x05Start\x12\x18.runtime.v1.StartRequest\x1a\x19.runtime.v1.StartResponse\"\x00\x12D\n" +
	"\aRestore\x12\x1a.runtime.v1.RestoreRequest\x1a\x1b.runtime.v1.RestoreResponse\"\x00\x12A\n" +
	"\x06Delete\x12\x19.runtime.v1.DeleteRequest\x1a\x1a.runtime.v1.DeleteResponse\"\x00\x12;\n" +
	"\x04Wait\x12\x17.runtime.v1.WaitRequest\x1a\x18.runtime.v1.WaitResponse\"\x00\x12M\n" +
	"\x04List\x12 .runtime.v1.ListSandboxesRequest\x1a!.runtime.v1.ListSandboxesResponse\"\x00\x12>\n" +
	"\x05Stats\x12\x18.runtime.v1.StatsRequest\x1a\x19.runtime.v1.StatsResponse\"\x00\x12E\n" +
	"\bRegister\x12\x1b.runtime.v1.RegisterRequest\x1a\x1a.runtime.v1.NormalResponse\"\x00\x12I\n" +
	"\n" +
	"Unregister\x12\x1d.runtime.v1.UnregisterRequest\x1a\x1a.runtime.v1.NormalResponse\"\x00\x12V\n" +
	"\rGetRegistered\x12 .runtime.v1.GetRegisteredRequest\x1a!.runtime.v1.GetRegisteredResponse\"\x00\x12M\n" +
	"\n" +
	"Checkpoint\x12\x1d.runtime.v1.CheckpointRequest\x1a\x1e.runtime.v1.CheckpointResponse\"\x00B1Z/runtime-launcher/api/proto/runtime/v1;runtimev1b\x06proto3"

var (
	file_sandbox_api_proto_rawDescOnce sync.Once
	file_sandbox_api_proto_rawDescData []byte
)

func file_sandbox_api_proto_rawDescGZIP() []byte {
	file_sandbox_api_proto_rawDescOnce.Do(func() {
		file_sandbox_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_api_proto_rawDesc), len(file_sandbox_api_proto_rawDesc)))
	})
	return file_sandbox_api_proto_rawDescData
}

var file_sandbox_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sandbox_api_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_sandbox_api_proto_goTypes = []any{
	(RootfsSrcType)(0),            // 0: runtime.v1.RootfsSrcType
	(SandboxState)(0),             // 1: runtime.v1.SandboxState
	(*S3Config)(nil),              // 2: runtime.v1.S3Config
	(*RootfsConfig)(nil),          // 3: runtime.v1.RootfsConfig
	(*Mount)(nil),                 // 4: runtime.v1.Mount
	(*StartRequest)(nil),          // 5: runtime.v1.StartRequest
	(*StartResponse)(nil),         // 6: runtime.v1.StartResponse
	(*RestoreRequest)(nil),        // 7: runtime.v1.RestoreRequest
	(*RestoreResponse)(nil),       // 8: runtime.v1.RestoreResponse
	(*DeleteRequest)(nil),         // 9: runtime.v1.DeleteRequest
	(*DeleteResponse)(nil),        // 10: runtime.v1.DeleteResponse
	(*WaitRequest)(nil),           // 11: runtime.v1.WaitRequest
	(*WaitResponse)(nil),          // 12: runtime.v1.WaitResponse
	(*SandboxTemplate)(nil),       // 13: runtime.v1.SandboxTemplate
	(*RegisterRequest)(nil),       // 14: runtime.v1.RegisterRequest
	(*NormalResponse)(nil),        // 15: runtime.v1.NormalResponse
	(*UnregisterRequest)(nil),     // 16: runtime.v1.UnregisterRequest
	(*GetRegisteredRequest)(nil),  // 17: runtime.v1.GetRegisteredRequest
	(*GetRegisteredResponse)(nil), // 18: runtime.v1.GetRegisteredResponse
	(*CheckpointRequest)(nil),     // 19: runtime.v1.CheckpointRequest
	(*CheckpointResponse)(nil),    // 20: runtime.v1.CheckpointResponse
	(*ListSandboxesRequest)(nil),  // 21: runtime.v1.ListSandboxesRequest
	(*ListSandboxesResponse)(nil), // 22: runtime.v1.ListSandboxesResponse
	(*SandboxStatus)(nil),         // 23: runtime.v1.SandboxStatus
	(*KeyValue)(nil),              // 24: runtime.v1.KeyValue
	(*LinuxSandboxResources)(nil), // 25: runtime.v1.LinuxSandboxResources
	(*HugepageLimit)(nil),         // 26: runtime.v1.HugepageLimit
	(*SandboxMetadata)(nil),       // 27: runtime.v1.SandboxMetadata
	(*SandboxMetadataList)(nil),   // 28: runtime.v1.SandboxMetadataList
	(*StatsRequest)(nil),          // 29: runtime.v1.StatsRequest
	(*StatsResponse)(nil),         // 30: runtime.v1.StatsResponse
	nil,                           // 31: runtime.v1.StartRequest.EnvsEntry
	nil,                           // 32: runtime.v1.StartRequest.ResourcesEntry
	nil,                           // 33: runtime.v1.StartRequest.LabelsEntry
	nil,                           // 34: runtime.v1.StartRequest.MetricLabelsEntry
	nil,                           // 35: runtime.v1.SandboxTemplate.EnvsEntry
	nil,                           // 36: runtime.v1.ListSandboxesRequest.SelectorEntry
	nil,                           // 37: runtime.v1.SandboxStatus.LabelsEntry
	nil,                           // 38: runtime.v1.SandboxStatus.MetricLabelsEntry
	nil,                           // 39: runtime.v1.LinuxSandboxResources.UnifiedEntry
	nil,                           // 40: runtime.v1.SandboxMetadata.LabelsEntry
	nil,                           // 41: runtime.v1.SandboxMetadata.MetricLabelsEntry
	nil,                           // 42: runtime.v1.SandboxMetadataList.SandboxesEntry
}
var file_sandbox_api_proto_depIdxs = []int32{
	0,  // 0: runtime.v1.RootfsConfig.type:type_name -> runtime.v1.RootfsSrcType
	2,  // 1: runtime.v1.RootfsConfig.s3_config:type_name -> runtime.v1.S3Config
	2,  // 2: runtime.v1.Mount.s3_config:type_name -> runtime.v1.S3Config
	3,  // 3: runtime.v1.StartRequest.rootfs:type_name -> runtime.v1.RootfsConfig
	31, // 4: runtime.v1.StartRequest.envs:type_name -> runtime.v1.StartRequest.EnvsEntry
	4,  // 5: runtime.v1.StartRequest.mounts:type_name -> runtime.v1.Mount
	32, // 6: runtime.v1.StartRequest.resources:type_name -> runtime.v1.StartRequest.ResourcesEntry
	33, // 7: runtime.v1.StartRequest.labels:type_name -> runtime.v1.StartRequest.LabelsEntry
	34, // 8: runtime.v1.StartRequest.metric_labels:type_name -> runtime.v1.StartRequest.MetricLabelsEntry
	5,  // 9: runtime.v1.RestoreRequest.sandbox:type_name -> runtime.v1.StartRequest
	3,  // 10: runtime.v1.SandboxTemplate.rootfs:type_name -> runtime.v1.RootfsConfig
	35, // 11: runtime.v1.SandboxTemplate.envs:type_name -> runtime.v1.SandboxTemplate.EnvsEntry
	4,  // 12: runtime.v1.SandboxTemplate.mounts:type_name -> runtime.v1.Mount
	13, // 13: runtime.v1.RegisterRequest.templates:type_name -> runtime.v1.SandboxTemplate
	13, // 14: runtime.v1.GetRegisteredResponse.templates:type_name -> runtime.v1.SandboxTemplate
	36, // 15: runtime.v1.ListSandboxesRequest.selector:type_name -> runtime.v1.ListSandboxesRequest.SelectorEntry
	23, // 16: runtime.v1.ListSandboxesResponse.sandboxes:type_name -> runtime.v1.SandboxStatus
	1,  // 17: runtime.v1.SandboxStatus.state:type_name -> runtime.v1.SandboxState
	37, // 18: runtime.v1.SandboxStatus.labels:type_name -> runtime.v1.SandboxStatus.LabelsEntry
	4,  // 19: runtime.v1.SandboxStatus.mounts:type_name -> runtime.v1.Mount
	24, // 20: runtime.v1.SandboxStatus.envs:type_name -> runtime.v1.KeyValue
	25, // 21: runtime.v1.SandboxStatus.resources:type_name -> runtime.v1.LinuxSandboxResources
	38, // 22: runtime.v1.SandboxStatus.metric_labels:type_name -> runtime.v1.SandboxStatus.MetricLabelsEntry
	26, // 23: runtime.v1.LinuxSandboxResources.hugepage_limits:type_name -> runtime.v1.HugepageLimit
	39, // 24: runtime.v1.LinuxSandboxResources.unified:type_name -> runtime.v1.LinuxSandboxResources.UnifiedEntry
	40, // 25: runtime.v1.SandboxMetadata.labels:type_name -> runtime.v1.SandboxMetadata.LabelsEntry
	41, // 26: runtime.v1.SandboxMetadata.metric_labels:type_name -> runtime.v1.SandboxMetadata.MetricLabelsEntry
	42, // 27: runtime.v1.SandboxMetadataList.sandboxes:type_name -> runtime.v1.SandboxMetadataList.SandboxesEntry
	27, // 28: runtime.v1.SandboxMetadataList.SandboxesEntry.value:type_name -> runtime.v1.SandboxMetadata
	5,  // 29: runtime.v1.SandboxService.Start:input_type -> runtime.v1.StartRequest
	7,  // 30: runtime.v1.SandboxService.Restore:input_type -> runtime.v1.RestoreRequest
	9,  // 31: runtime.v1.SandboxService.Delete:input_type -> runtime.v1.DeleteRequest
	11, // 32: runtime.v1.SandboxService.Wait:input_type -> runtime.v1.WaitRequest
	21, // 33: runtime.v1.SandboxService.List:input_type -> runtime.v1.ListSandboxesRequest
	29, // 34: runtime.v1.SandboxService.Stats:input_type -> runtime.v1.StatsRequest
	14, // 35: runtime.v1.SandboxService.Register:input_type -> runtime.v1.RegisterRequest
	16, // 36: runtime.v1.SandboxService.Unregister:input_type -> runtime.v1.UnregisterRequest
	17, // 37: runtime.v1.SandboxService.GetRegistered:input_type -> runtime.v1.GetRegisteredRequest
	19, // 38: runtime.v1.SandboxService.Checkpoint:input_type -> runtime.v1.CheckpointRequest
	6,  // 39: runtime.v1.SandboxService.Start:output_type -> runtime.v1.StartResponse
	8,  // 40: runtime.v1.SandboxService.Restore:output_type -> runtime.v1.RestoreResponse
	10, // 41: runtime.v1.SandboxService.Delete:output_type -> runtime.v1.DeleteResponse
	12, // 42: runtime.v1.SandboxService.Wait:output_type -> runtime.v1.WaitResponse
	22, // 43: runtime.v1.SandboxService.List:output_type -> runtime.v1.ListSandboxesResponse
	30, // 44: runtime.v1.SandboxService.Stats:output_type -> runtime.v1.StatsResponse
	15, // 45: runtime.v1.SandboxService.Register:output_type -> runtime.v1.NormalResponse
	15, // 46: runtime.v1.SandboxService.Unregister:output_type -> runtime.v1.NormalResponse
	18, // 47: runtime.v1.SandboxService.GetRegistered:output_type -> runtime.v1.GetRegisteredResponse
	20, // 48: runtime.v1.SandboxService.Checkpoint:output_type -> runtime.v1.CheckpointResponse
	39, // [39:49] is the sub-list for method output_type
	29, // [29:39] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_sandbox_api_proto_init() }
func file_sandbox_api_proto_init() {
	if File_sandbox_api_proto != nil {
		return
	}
	file_sandbox_api_proto_msgTypes[1].OneofWrappers = []any{
		(*RootfsConfig_ImageUrl)(nil),
		(*RootfsConfig_S3Config)(nil),
		(*RootfsConfig_Path)(nil),
	}
	file_sandbox_api_proto_msgTypes[2].OneofWrappers = []any{
		(*Mount_HostPath)(nil),
		(*Mount_S3Config)(nil),
		(*Mount_ImageUrl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_api_proto_rawDesc), len(file_sandbox_api_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_api_proto_goTypes,
		DependencyIndexes: file_sandbox_api_proto_depIdxs,
		EnumInfos:         file_sandbox_api_proto_enumTypes,
		MessageInfos:      file_sandbox_api_proto_msgTypes,
	}.Build()
	File_sandbox_api_proto = out.File
	file_sandbox_api_proto_goTypes = nil
	file_sandbox_api_proto_depIdxs = nil
}
