// Copyright (c) 2026 Huawei Technologies Co., Ltd. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.14.0
// source: sandbox_api.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SandboxState is the persisted lifecycle state of a sandbox.
type SandboxState int32

const (
	SandboxState_SANDBOX_STATE_RUNNING SandboxState = 0
	SandboxState_SANDBOX_STATE_EXITED  SandboxState = 1
	SandboxState_SANDBOX_STATE_UNKNOWN SandboxState = 2
)

// Enum value maps for SandboxState.
var (
	SandboxState_name = map[int32]string{
		0: "SANDBOX_STATE_RUNNING",
		1: "SANDBOX_STATE_EXITED",
		2: "SANDBOX_STATE_UNKNOWN",
	}
	SandboxState_value = map[string]int32{
		"SANDBOX_STATE_RUNNING": 0,
		"SANDBOX_STATE_EXITED":  1,
		"SANDBOX_STATE_UNKNOWN": 2,
	}
)

func (x SandboxState) Enum() *SandboxState {
	p := new(SandboxState)
	*p = x
	return p
}

func (x SandboxState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxState) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_api_proto_enumTypes[0].Descriptor()
}

func (SandboxState) Type() protoreflect.EnumType {
	return &file_sandbox_api_proto_enumTypes[0]
}

func (x SandboxState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandboxState.Descriptor instead.
func (SandboxState) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{0}
}

// SandboxStartRequest is the flat sandbox start request (mirrors sandboxd
// StartRequest field numbers exactly). Renamed from StartRequest only to avoid
// a C++ namespace clash with the legacy runtime.v1.StartRequest.
type SandboxStartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SandboxID is an optional caller-provided sandbox ID; sandboxd generates one when empty.
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// TemplateID is the registered SandboxTemplate ID to start from. Only requests
	// with this field set are eligible to reuse a registered seed/fork path.
	TemplateId string `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// Runtime is the runtime handler name, such as runsc.
	Runtime string `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// Rootfs is the root filesystem source used by the sandbox.
	Rootfs *RootfsConfig `protobuf:"bytes,4,opt,name=rootfs,proto3" json:"rootfs,omitempty"`
	// Command is the executable and arguments to run inside the sandbox.
	Command []string `protobuf:"bytes,5,rep,name=command,proto3" json:"command,omitempty"`
	// Cwd is the working directory inside the sandbox.
	Cwd string `protobuf:"bytes,6,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Envs contains environment variables for the sandbox process.
	Envs map[string]string `protobuf:"bytes,7,rep,name=envs,proto3" json:"envs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Mounts contains additional mounts attached to the sandbox.
	Mounts []*Mount `protobuf:"bytes,8,rep,name=mounts,proto3" json:"mounts,omitempty"`
	// Resources contains sandbox resource requests. CPU is millicores and memory is MB.
	Resources map[string]float64 `protobuf:"bytes,9,rep,name=resources,proto3" json:"resources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	// Stdout is the redirect path for stdout. Empty means stdout is discarded to /dev/null.
	Stdout string `protobuf:"bytes,10,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// Stderr is the redirect path for stderr. Empty means stderr is discarded to /dev/null.
	Stderr string `protobuf:"bytes,11,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// ExtraConfig is a JSON string for runtime-specific configuration.
	ExtraConfig string `protobuf:"bytes,12,opt,name=extra_config,json=extraConfig,proto3" json:"extra_config,omitempty"`
	// Network is the network mode. Empty means sandbox network; supported values are sandbox, host, and none.
	Network string `protobuf:"bytes,13,opt,name=network,proto3" json:"network,omitempty"`
	// TraceID is an optional distributed trace ID.
	TraceId string `protobuf:"bytes,14,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Ports contains port forwarding entries in "protocol:dstPort:targetPort" format.
	Ports []string `protobuf:"bytes,15,rep,name=ports,proto3" json:"ports,omitempty"`
	// Labels contains sandbox labels used for selection and runtime metadata.
	Labels map[string]string `protobuf:"bytes,16,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// MetricLabels contains sandbox metadata intended for metric dimensions.
	MetricLabels  map[string]string `protobuf:"bytes,17,rep,name=metric_labels,json=metricLabels,proto3" json:"metric_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxStartRequest) Reset() {
	*x = SandboxStartRequest{}
	mi := &file_sandbox_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxStartRequest) ProtoMessage() {}

func (x *SandboxStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxStartRequest.ProtoReflect.Descriptor instead.
func (*SandboxStartRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{0}
}

func (x *SandboxStartRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxStartRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SandboxStartRequest) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *SandboxStartRequest) GetRootfs() *RootfsConfig {
	if x != nil {
		return x.Rootfs
	}
	return nil
}

func (x *SandboxStartRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *SandboxStartRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *SandboxStartRequest) GetEnvs() map[string]string {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *SandboxStartRequest) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *SandboxStartRequest) GetResources() map[string]float64 {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *SandboxStartRequest) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *SandboxStartRequest) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *SandboxStartRequest) GetExtraConfig() string {
	if x != nil {
		return x.ExtraConfig
	}
	return ""
}

func (x *SandboxStartRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *SandboxStartRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SandboxStartRequest) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *SandboxStartRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SandboxStartRequest) GetMetricLabels() map[string]string {
	if x != nil {
		return x.MetricLabels
	}
	return nil
}

// RestoreRequest describes a sandbox restore (from checkpoint) request.
type RestoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sandbox is the sandbox spec to create from the checkpoint (same shape as Start).
	Sandbox *SandboxStartRequest `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	// CheckpointDir is the directory containing checkpoint artifacts.
	CheckpointDir string `protobuf:"bytes,2,opt,name=checkpoint_dir,json=checkpointDir,proto3" json:"checkpoint_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_sandbox_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{1}
}

func (x *RestoreRequest) GetSandbox() *SandboxStartRequest {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *RestoreRequest) GetCheckpointDir() string {
	if x != nil {
		return x.CheckpointDir
	}
	return ""
}

// RestoreResponse is returned after sandbox restore.
type RestoreResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Code is 0 on success.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Message contains details about the restore result.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// ID is the unique sandbox ID.
	Id            string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_sandbox_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{2}
}

func (x *RestoreResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RestoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RestoreResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// SandboxTemplate describes a reusable sandbox template registered in sandboxd
// (warm-up). Mirrors sandboxd's SandboxTemplate; fields/tags match exactly.
type SandboxTemplate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the registered template ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Runtime is the runtime handler name, such as runsc.
	Runtime string `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// Rootfs is the root filesystem source used by the template.
	Rootfs *RootfsConfig `protobuf:"bytes,3,opt,name=rootfs,proto3" json:"rootfs,omitempty"`
	// MakeSeed asks sandboxd to pre-create a seed sandbox when supported.
	MakeSeed bool `protobuf:"varint,4,opt,name=make_seed,json=makeSeed,proto3" json:"make_seed,omitempty"`
	// Command is the executable and arguments to run inside the sandbox.
	Command []string `protobuf:"bytes,5,rep,name=command,proto3" json:"command,omitempty"`
	// Envs contains environment variables for the sandbox process.
	Envs map[string]string `protobuf:"bytes,6,rep,name=envs,proto3" json:"envs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Cwd is the working directory inside the sandbox.
	Cwd string `protobuf:"bytes,7,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Mounts contains additional mounts attached to the sandbox.
	Mounts        []*Mount `protobuf:"bytes,8,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxTemplate) Reset() {
	*x = SandboxTemplate{}
	mi := &file_sandbox_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxTemplate) ProtoMessage() {}

func (x *SandboxTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxTemplate.ProtoReflect.Descriptor instead.
func (*SandboxTemplate) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{3}
}

func (x *SandboxTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SandboxTemplate) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *SandboxTemplate) GetRootfs() *RootfsConfig {
	if x != nil {
		return x.Rootfs
	}
	return nil
}

func (x *SandboxTemplate) GetMakeSeed() bool {
	if x != nil {
		return x.MakeSeed
	}
	return false
}

func (x *SandboxTemplate) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *SandboxTemplate) GetEnvs() map[string]string {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *SandboxTemplate) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *SandboxTemplate) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

// SandboxRegisterRequest describes sandbox template registration.
// (Renamed from RegisterRequest to avoid a runtime.v1 C++ symbol clash with the
// legacy runtime_launcher_interface.proto RegisterRequest.)
type SandboxRegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Templates contains sandbox templates to register.
	Templates     []*SandboxTemplate `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxRegisterRequest) Reset() {
	*x = SandboxRegisterRequest{}
	mi := &file_sandbox_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxRegisterRequest) ProtoMessage() {}

func (x *SandboxRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxRegisterRequest.ProtoReflect.Descriptor instead.
func (*SandboxRegisterRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{4}
}

func (x *SandboxRegisterRequest) GetTemplates() []*SandboxTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

// SandboxNormalResponse is returned by template registration operations.
// (Renamed from NormalResponse to avoid the legacy runtime.v1 clash.)
type SandboxNormalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxNormalResponse) Reset() {
	*x = SandboxNormalResponse{}
	mi := &file_sandbox_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxNormalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxNormalResponse) ProtoMessage() {}

func (x *SandboxNormalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxNormalResponse.ProtoReflect.Descriptor instead.
func (*SandboxNormalResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{5}
}

func (x *SandboxNormalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SandboxNormalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SandboxUnregisterRequest describes sandbox template removal.
// (Renamed from UnregisterRequest to avoid the legacy runtime.v1 clash.)
type SandboxUnregisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IDs contains sandbox template IDs to unregister.
	Ids           []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxUnregisterRequest) Reset() {
	*x = SandboxUnregisterRequest{}
	mi := &file_sandbox_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxUnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxUnregisterRequest) ProtoMessage() {}

func (x *SandboxUnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxUnregisterRequest.ProtoReflect.Descriptor instead.
func (*SandboxUnregisterRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{6}
}

func (x *SandboxUnregisterRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// SandboxGetRegisteredRequest describes a registered sandbox template list request.
// (Renamed from GetRegisteredRequest to avoid the legacy runtime.v1 clash.)
type SandboxGetRegisteredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxGetRegisteredRequest) Reset() {
	*x = SandboxGetRegisteredRequest{}
	mi := &file_sandbox_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxGetRegisteredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxGetRegisteredRequest) ProtoMessage() {}

func (x *SandboxGetRegisteredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxGetRegisteredRequest.ProtoReflect.Descriptor instead.
func (*SandboxGetRegisteredRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{7}
}

// SandboxGetRegisteredResponse contains registered sandbox templates.
// (Renamed from GetRegisteredResponse to avoid the legacy runtime.v1 clash.)
type SandboxGetRegisteredResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Templates contains registered sandbox templates.
	Templates     []*SandboxTemplate `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxGetRegisteredResponse) Reset() {
	*x = SandboxGetRegisteredResponse{}
	mi := &file_sandbox_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxGetRegisteredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxGetRegisteredResponse) ProtoMessage() {}

func (x *SandboxGetRegisteredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxGetRegisteredResponse.ProtoReflect.Descriptor instead.
func (*SandboxGetRegisteredResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{8}
}

func (x *SandboxGetRegisteredResponse) GetTemplates() []*SandboxTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

// SandboxCheckpointRequest describes a sandbox checkpoint request.
// (Renamed from CheckpointRequest to avoid the legacy runtime.v1 clash.)
type SandboxCheckpointRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the sandbox ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// CheckpointDir is the output directory for checkpoint artifacts.
	CheckpointDir string `protobuf:"bytes,2,opt,name=checkpoint_dir,json=checkpointDir,proto3" json:"checkpoint_dir,omitempty"`
	// Timeout is the number of seconds to wait for checkpoint completion.
	Timeout int64 `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Compress enables checkpoint artifact compression when true.
	Compress bool `protobuf:"varint,4,opt,name=compress,proto3" json:"compress,omitempty"`
	// TraceID is an optional distributed trace ID.
	TraceId       string `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxCheckpointRequest) Reset() {
	*x = SandboxCheckpointRequest{}
	mi := &file_sandbox_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCheckpointRequest) ProtoMessage() {}

func (x *SandboxCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCheckpointRequest.ProtoReflect.Descriptor instead.
func (*SandboxCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{9}
}

func (x *SandboxCheckpointRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SandboxCheckpointRequest) GetCheckpointDir() string {
	if x != nil {
		return x.CheckpointDir
	}
	return ""
}

func (x *SandboxCheckpointRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *SandboxCheckpointRequest) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

func (x *SandboxCheckpointRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// SandboxCheckpointResponse is returned after sandbox checkpoint.
// (Renamed from CheckpointResponse to avoid the legacy runtime.v1 clash.)
type SandboxCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxCheckpointResponse) Reset() {
	*x = SandboxCheckpointResponse{}
	mi := &file_sandbox_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCheckpointResponse) ProtoMessage() {}

func (x *SandboxCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCheckpointResponse.ProtoReflect.Descriptor instead.
func (*SandboxCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{10}
}

func (x *SandboxCheckpointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SandboxCheckpointResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListSandboxesRequest describes a sandbox list request.
type ListSandboxesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID filters by sandbox ID when set.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Selector filters sandboxes by labels. Empty selector lists all sandboxes.
	Selector      map[string]string `protobuf:"bytes,10,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesRequest) Reset() {
	*x = ListSandboxesRequest{}
	mi := &file_sandbox_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesRequest) ProtoMessage() {}

func (x *ListSandboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesRequest.ProtoReflect.Descriptor instead.
func (*ListSandboxesRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{11}
}

func (x *ListSandboxesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListSandboxesRequest) GetSelector() map[string]string {
	if x != nil {
		return x.Selector
	}
	return nil
}

// ListSandboxesResponse contains sandbox list results.
type ListSandboxesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sandboxes contains matching sandbox statuses.
	Sandboxes     []*SandboxStatus `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesResponse) Reset() {
	*x = ListSandboxesResponse{}
	mi := &file_sandbox_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesResponse) ProtoMessage() {}

func (x *ListSandboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesResponse.ProtoReflect.Descriptor instead.
func (*ListSandboxesResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{12}
}

func (x *ListSandboxesResponse) GetSandboxes() []*SandboxStatus {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

// SandboxStatus describes the current status and metadata of a sandbox.
type SandboxStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the sandbox ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Command is the executable and arguments configured for the sandbox.
	Command []string `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	// Runtime is the runtime handler name.
	Runtime string `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// State is the current sandbox lifecycle state.
	State SandboxState `protobuf:"varint,4,opt,name=state,proto3,enum=runtime.v1.SandboxState" json:"state,omitempty"`
	// StartedAt is the sandbox start timestamp in Unix seconds.
	StartedAt int64 `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// FinishedAt is the sandbox finish timestamp in Unix seconds.
	FinishedAt int64 `protobuf:"varint,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	// ExitCode is the sandbox process exit code when available.
	ExitCode int32 `protobuf:"varint,7,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Message contains details about the sandbox state.
	Message string `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	// Labels contains sandbox labels.
	Labels map[string]string `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Mounts contains additional mounts attached to the sandbox.
	Mounts []*Mount `protobuf:"bytes,10,rep,name=mounts,proto3" json:"mounts,omitempty"`
	// Envs contains environment variables configured for the sandbox.
	Envs []*KeyValue `protobuf:"bytes,11,rep,name=envs,proto3" json:"envs,omitempty"`
	// Stdout is the configured stdout redirect path.
	Stdout string `protobuf:"bytes,12,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// Stderr is the configured stderr redirect path.
	Stderr string `protobuf:"bytes,13,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// Resources contains Linux resource settings for the sandbox.
	Resources *LinuxSandboxResources `protobuf:"bytes,14,opt,name=resources,proto3" json:"resources,omitempty"`
	// MetricLabels contains sandbox metadata intended for metric dimensions.
	MetricLabels  map[string]string `protobuf:"bytes,15,rep,name=metric_labels,json=metricLabels,proto3" json:"metric_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxStatus) Reset() {
	*x = SandboxStatus{}
	mi := &file_sandbox_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxStatus) ProtoMessage() {}

func (x *SandboxStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxStatus.ProtoReflect.Descriptor instead.
func (*SandboxStatus) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{13}
}

func (x *SandboxStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SandboxStatus) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *SandboxStatus) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *SandboxStatus) GetState() SandboxState {
	if x != nil {
		return x.State
	}
	return SandboxState_SANDBOX_STATE_RUNNING
}

func (x *SandboxStatus) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *SandboxStatus) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *SandboxStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *SandboxStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SandboxStatus) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SandboxStatus) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *SandboxStatus) GetEnvs() []*KeyValue {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *SandboxStatus) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *SandboxStatus) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *SandboxStatus) GetResources() *LinuxSandboxResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *SandboxStatus) GetMetricLabels() map[string]string {
	if x != nil {
		return x.MetricLabels
	}
	return nil
}

// LinuxSandboxResources describes Linux resource settings for a sandbox.
type LinuxSandboxResources struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CPUPeriod is the CPU CFS period in microseconds.
	CpuPeriod uint64 `protobuf:"varint,1,opt,name=cpu_period,json=cpuPeriod,proto3" json:"cpu_period,omitempty"`
	// CPUQuota is the CPU CFS quota in microseconds.
	CpuQuota int64 `protobuf:"varint,2,opt,name=cpu_quota,json=cpuQuota,proto3" json:"cpu_quota,omitempty"`
	// CPUShares is the relative CPU share weight.
	CpuShares uint64 `protobuf:"varint,3,opt,name=cpu_shares,json=cpuShares,proto3" json:"cpu_shares,omitempty"`
	// MemoryLimitInBytes is the memory limit in bytes.
	MemoryLimitInBytes int64 `protobuf:"varint,4,opt,name=memory_limit_in_bytes,json=memoryLimitInBytes,proto3" json:"memory_limit_in_bytes,omitempty"`
	// OomScoreAdj is the OOM score adjustment.
	OomScoreAdj int64 `protobuf:"varint,5,opt,name=oom_score_adj,json=oomScoreAdj,proto3" json:"oom_score_adj,omitempty"`
	// CpusetCpus is the allowed CPU set.
	CpusetCpus string `protobuf:"bytes,6,opt,name=cpuset_cpus,json=cpusetCpus,proto3" json:"cpuset_cpus,omitempty"`
	// CpusetMems is the allowed memory node set.
	CpusetMems string `protobuf:"bytes,7,opt,name=cpuset_mems,json=cpusetMems,proto3" json:"cpuset_mems,omitempty"`
	// HugepageLimits contains hugepage limits by page size.
	HugepageLimits []*HugepageLimit `protobuf:"bytes,8,rep,name=hugepage_limits,json=hugepageLimits,proto3" json:"hugepage_limits,omitempty"`
	// Unified contains cgroup v2 unified controller settings.
	Unified map[string]string `protobuf:"bytes,9,rep,name=unified,proto3" json:"unified,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// MemorySwapLimitInBytes is the memory plus swap limit in bytes.
	MemorySwapLimitInBytes int64 `protobuf:"varint,10,opt,name=memory_swap_limit_in_bytes,json=memorySwapLimitInBytes,proto3" json:"memory_swap_limit_in_bytes,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LinuxSandboxResources) Reset() {
	*x = LinuxSandboxResources{}
	mi := &file_sandbox_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinuxSandboxResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinuxSandboxResources) ProtoMessage() {}

func (x *LinuxSandboxResources) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinuxSandboxResources.ProtoReflect.Descriptor instead.
func (*LinuxSandboxResources) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{14}
}

func (x *LinuxSandboxResources) GetCpuPeriod() uint64 {
	if x != nil {
		return x.CpuPeriod
	}
	return 0
}

func (x *LinuxSandboxResources) GetCpuQuota() int64 {
	if x != nil {
		return x.CpuQuota
	}
	return 0
}

func (x *LinuxSandboxResources) GetCpuShares() uint64 {
	if x != nil {
		return x.CpuShares
	}
	return 0
}

func (x *LinuxSandboxResources) GetMemoryLimitInBytes() int64 {
	if x != nil {
		return x.MemoryLimitInBytes
	}
	return 0
}

func (x *LinuxSandboxResources) GetOomScoreAdj() int64 {
	if x != nil {
		return x.OomScoreAdj
	}
	return 0
}

func (x *LinuxSandboxResources) GetCpusetCpus() string {
	if x != nil {
		return x.CpusetCpus
	}
	return ""
}

func (x *LinuxSandboxResources) GetCpusetMems() string {
	if x != nil {
		return x.CpusetMems
	}
	return ""
}

func (x *LinuxSandboxResources) GetHugepageLimits() []*HugepageLimit {
	if x != nil {
		return x.HugepageLimits
	}
	return nil
}

func (x *LinuxSandboxResources) GetUnified() map[string]string {
	if x != nil {
		return x.Unified
	}
	return nil
}

func (x *LinuxSandboxResources) GetMemorySwapLimitInBytes() int64 {
	if x != nil {
		return x.MemorySwapLimitInBytes
	}
	return 0
}

// SandboxMetadata contains the persisted metadata for a sandbox.
type SandboxMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the sandbox ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// RuntimeHandler is the runtime handler name.
	RuntimeHandler string `protobuf:"bytes,3,opt,name=runtime_handler,json=runtimeHandler,proto3" json:"runtime_handler,omitempty"`
	// Labels contains sandbox labels.
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Stdout is the configured stdout redirect path.
	Stdout string `protobuf:"bytes,6,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// Stderr is the configured stderr redirect path.
	Stderr string `protobuf:"bytes,7,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// MetricLabels contains sandbox metadata intended for metric dimensions.
	MetricLabels  map[string]string `protobuf:"bytes,8,rep,name=metric_labels,json=metricLabels,proto3" json:"metric_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxMetadata) Reset() {
	*x = SandboxMetadata{}
	mi := &file_sandbox_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxMetadata) ProtoMessage() {}

func (x *SandboxMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxMetadata.ProtoReflect.Descriptor instead.
func (*SandboxMetadata) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{15}
}

func (x *SandboxMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SandboxMetadata) GetRuntimeHandler() string {
	if x != nil {
		return x.RuntimeHandler
	}
	return ""
}

func (x *SandboxMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SandboxMetadata) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *SandboxMetadata) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *SandboxMetadata) GetMetricLabels() map[string]string {
	if x != nil {
		return x.MetricLabels
	}
	return nil
}

// SandboxMetadataList contains persisted sandbox metadata entries.
type SandboxMetadataList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sandboxes maps sandbox ID to sandbox metadata.
	Sandboxes     map[string]*SandboxMetadata `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxMetadataList) Reset() {
	*x = SandboxMetadataList{}
	mi := &file_sandbox_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxMetadataList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxMetadataList) ProtoMessage() {}

func (x *SandboxMetadataList) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxMetadataList.ProtoReflect.Descriptor instead.
func (*SandboxMetadataList) Descriptor() ([]byte, []int) {
	return file_sandbox_api_proto_rawDescGZIP(), []int{16}
}

func (x *SandboxMetadataList) GetSandboxes() map[string]*SandboxMetadata {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

var File_sandbox_api_proto protoreflect.FileDescriptor

const file_sandbox_api_proto_rawDesc = "" +
	"\n" +
	"\x11sandbox_api.proto\x12\n" +
	"runtime.v1\x1a runtime_launcher_interface.proto\"\xb3\a\n" +
	"\x13SandboxStartRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x18\n" +
	"\aruntime\x18\x03 \x01(\tR\aruntime\x120\n" +
	"\x06rootfs\x18\x04 \x01(\v2\x18.runtime.v1.RootfsConfigR\x06rootfs\x12\x18\n" +
	"\acommand\x18\x05 \x03(\tR\acommand\x12\x10\n" +
	"\x03cwd\x18\x06 \x01(\tR\x03cwd\x12=\n" +
	"\x04envs\x18\a \x03(\v2).runtime.v1.SandboxStartRequest.EnvsEntryR\x04envs\x12)\n" +
	"\x06mounts\x18\b \x03(\v2\x11.runtime.v1.MountR\x06mounts\x12L\n" +
	"\tresources\x18\t \x03(\v2..runtime.v1.SandboxStartRequest.ResourcesEntryR\tresources\x12\x16\n" +
	"\x06stdout\x18\n" +
	" \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\v \x01(\tR\x06stderr\x12!\n" +
	"\fextra_config\x18\f \x01(\tR\vextraConfig\x12\x18\n" +
	"\anetwork\x18\r \x01(\tR\anetwork\x12\x19\n" +
	"\btrace_id\x18\x0e \x01(\tR\atraceId\x12\x14\n" +
	"\x05ports\x18\x0f \x03(\tR\x05ports\x12C\n" +
	"\x06labels\x18\x10 \x03(\v2+.runtime.v1.SandboxStartRequest.LabelsEntryR\x06labels\x12V\n" +
	"\rmetric_labels\x18\x11 \x03(\v21.runtime.v1.SandboxStartRequest.MetricLabelsEntryR\fmetricLabels\x1a7\n" +
	"\tEnvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11MetricLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x0eRestoreRequest\x129\n" +
	"\asandbox\x18\x01 \x01(\v2\x1f.runtime.v1.SandboxStartRequestR\asandbox\x12%\n" +
	"\x0echeckpoint_dir\x18\x02 \x01(\tR\rcheckpointDir\"O\n" +
	"\x0fRestoreResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"\xd5\x02\n" +
	"\x0fSandboxTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aruntime\x18\x02 \x01(\tR\aruntime\x120\n" +
	"\x06rootfs\x18\x03 \x01(\v2\x18.runtime.v1.RootfsConfigR\x06rootfs\x12\x1b\n" +
	"\tmake_seed\x18\x04 \x01(\bR\bmakeSeed\x12\x18\n" +
	"\acommand\x18\x05 \x03(\tR\acommand\x129\n" +
	"\x04envs\x18\x06 \x03(\v2%.runtime.v1.SandboxTemplate.EnvsEntryR\x04envs\x12\x10\n" +
	"\x03cwd\x18\a \x01(\tR\x03cwd\x12)\n" +
	"\x06mounts\x18\b \x03(\v2\x11.runtime.v1.MountR\x06mounts\x1a7\n" +
	"\tEnvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\x16SandboxRegisterRequest\x129\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1b.runtime.v1.SandboxTemplateR\ttemplates\"K\n" +
	"\x15SandboxNormalResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x18SandboxUnregisterRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\x1d\n" +
	"\x1bSandboxGetRegisteredRequest\"Y\n" +
	"\x1cSandboxGetRegisteredResponse\x129\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1b.runtime.v1.SandboxTemplateR\ttemplates\"\xa2\x01\n" +
	"\x18SandboxCheckpointRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0echeckpoint_dir\x18\x02 \x01(\tR\rcheckpointDir\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x03R\atimeout\x12\x1a\n" +
	"\bcompress\x18\x04 \x01(\bR\bcompress\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\"O\n" +
	"\x19SandboxCheckpointResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xaf\x01\n" +
	"\x14ListSandboxesRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12J\n" +
	"\bselector\x18\n" +
	" \x03(\v2..runtime.v1.ListSandboxesRequest.SelectorEntryR\bselector\x1a;\n" +
	"\rSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x15ListSandboxesResponse\x127\n" +
	"\tsandboxes\x18\x01 \x03(\v2\x19.runtime.v1.SandboxStatusR\tsandboxes\"\xcd\x05\n" +
	"\rSandboxStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x18\n" +
	"\aruntime\x18\x03 \x01(\tR\aruntime\x12.\n" +
	"\x05state\x18\x04 \x01(\x0e2\x18.runtime.v1.SandboxStateR\x05state\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x06 \x01(\x03R\n" +
	"finishedAt\x12\x1b\n" +
	"\texit_code\x18\a \x01(\x05R\bexitCode\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x12=\n" +
	"\x06labels\x18\t \x03(\v2%.runtime.v1.SandboxStatus.LabelsEntryR\x06labels\x12)\n" +
	"\x06mounts\x18\n" +
	" \x03(\v2\x11.runtime.v1.MountR\x06mounts\x12(\n" +
	"\x04envs\x18\v \x03(\v2\x14.runtime.v1.KeyValueR\x04envs\x12\x16\n" +
	"\x06stdout\x18\f \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\r \x01(\tR\x06stderr\x12?\n" +
	"\tresources\x18\x0e \x01(\v2!.runtime.v1.LinuxSandboxResourcesR\tresources\x12P\n" +
	"\rmetric_labels\x18\x0f \x03(\v2+.runtime.v1.SandboxStatus.MetricLabelsEntryR\fmetricLabels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11MetricLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x04\n" +
	"\x15LinuxSandboxResources\x12\x1d\n" +
	"\n" +
	"cpu_period\x18\x01 \x01(\x04R\tcpuPeriod\x12\x1b\n" +
	"\tcpu_quota\x18\x02 \x01(\x03R\bcpuQuota\x12\x1d\n" +
	"\n" +
	"cpu_shares\x18\x03 \x01(\x04R\tcpuShares\x121\n" +
	"\x15memory_limit_in_bytes\x18\x04 \x01(\x03R\x12memoryLimitInBytes\x12\"\n" +
	"\room_score_adj\x18\x05 \x01(\x03R\voomScoreAdj\x12\x1f\n" +
	"\vcpuset_cpus\x18\x06 \x01(\tR\n" +
	"cpusetCpus\x12\x1f\n" +
	"\vcpuset_mems\x18\a \x01(\tR\n" +
	"cpusetMems\x12B\n" +
	"\x0fhugepage_limits\x18\b \x03(\v2\x19.runtime.v1.HugepageLimitR\x0ehugepageLimits\x12H\n" +
	"\aunified\x18\t \x03(\v2..runtime.v1.LinuxSandboxResources.UnifiedEntryR\aunified\x12:\n" +
	"\x1amemory_swap_limit_in_bytes\x18\n" +
	" \x01(\x03R\x16memorySwapLimitInBytes\x1a:\n" +
	"\fUnifiedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x03\n" +
	"\x0fSandboxMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fruntime_handler\x18\x03 \x01(\tR\x0eruntimeHandler\x12?\n" +
	"\x06labels\x18\x04 \x03(\v2'.runtime.v1.SandboxMetadata.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06stdout\x18\x06 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\a \x01(\tR\x06stderr\x12R\n" +
	"\rmetric_labels\x18\b \x03(\v2-.runtime.v1.SandboxMetadata.MetricLabelsEntryR\fmetricLabels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11MetricLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbe\x01\n" +
	"\x13SandboxMetadataList\x12L\n" +
	"\tsandboxes\x18\x01 \x03(\v2..runtime.v1.SandboxMetadataList.SandboxesEntryR\tsandboxes\x1aY\n" +
	"\x0eSandboxesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.runtime.v1.SandboxMetadataR\x05value:\x028\x01*^\n" +
	"\fSandboxState\x12\x19\n" +
	"\x15SANDBOX_STATE_RUNNING\x10\x00\x12\x18\n" +
	"\x14SANDBOX_STATE_EXITED\x10\x01\x12\x19\n" +
	"\x15SANDBOX_STATE_UNKNOWN\x10\x022\x9d\x06\n" +
	"\x0eSandboxService\x12E\n" +
	"\x05Start\x12\x1f.runtime.v1.SandboxStartRequest\x1a\x19.runtime.v1.StartResponse\"\x00\x12D\n" +
	"\aRestore\x12\x1a.runtime.v1.RestoreRequest\x1a\x1b.runtime.v1.RestoreResponse\"\x00\x12A\n" +
	"\x06Delete\x12\x19.runtime.v1.DeleteRequest\x1a\x1a.runtime.v1.DeleteResponse\"\x00\x12;\n" +
	"\x04Wait\x12\x17.runtime.v1.WaitRequest\x1a\x18.runtime.v1.WaitResponse\"\x00\x12M\n" +
	"\x04List\x12 .runtime.v1.ListSandboxesRequest\x1a!.runtime.v1.ListSandboxesResponse\"\x00\x12>\n" +
	"\x05Stats\x12\x18.runtime.v1.StatsRequest\x1a\x19.runtime.v1.StatsResponse\"\x00\x12S\n" +
	"\bRegister\x12\".runtime.v1.SandboxRegisterRequest\x1a!.runtime.v1.SandboxNormalResponse\"\x00\x12W\n" +
	"\n" +
	"Unregister\x12$.runtime.v1.SandboxUnregisterRequest\x1a!.runtime.v1.SandboxNormalResponse\"\x00\x12d\n" +
	"\rGetRegistered\x12'.runtime.v1.SandboxGetRegisteredRequest\x1a(.runtime.v1.SandboxGetRegisteredResponse\"\x00\x12[\n" +
	"\n" +
	"Checkpoint\x12$.runtime.v1.SandboxCheckpointRequest\x1a%.runtime.v1.SandboxCheckpointResponse\"\x00B1Z/runtime-launcher/api/proto/runtime/v1;runtimev1b\x06proto3"

var (
	file_sandbox_api_proto_rawDescOnce sync.Once
	file_sandbox_api_proto_rawDescData []byte
)

func file_sandbox_api_proto_rawDescGZIP() []byte {
	file_sandbox_api_proto_rawDescOnce.Do(func() {
		file_sandbox_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_api_proto_rawDesc), len(file_sandbox_api_proto_rawDesc)))
	})
	return file_sandbox_api_proto_rawDescData
}

var file_sandbox_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sandbox_api_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_sandbox_api_proto_goTypes = []any{
	(SandboxState)(0),                    // 0: runtime.v1.SandboxState
	(*SandboxStartRequest)(nil),          // 1: runtime.v1.SandboxStartRequest
	(*RestoreRequest)(nil),               // 2: runtime.v1.RestoreRequest
	(*RestoreResponse)(nil),              // 3: runtime.v1.RestoreResponse
	(*SandboxTemplate)(nil),              // 4: runtime.v1.SandboxTemplate
	(*SandboxRegisterRequest)(nil),       // 5: runtime.v1.SandboxRegisterRequest
	(*SandboxNormalResponse)(nil),        // 6: runtime.v1.SandboxNormalResponse
	(*SandboxUnregisterRequest)(nil),     // 7: runtime.v1.SandboxUnregisterRequest
	(*SandboxGetRegisteredRequest)(nil),  // 8: runtime.v1.SandboxGetRegisteredRequest
	(*SandboxGetRegisteredResponse)(nil), // 9: runtime.v1.SandboxGetRegisteredResponse
	(*SandboxCheckpointRequest)(nil),     // 10: runtime.v1.SandboxCheckpointRequest
	(*SandboxCheckpointResponse)(nil),    // 11: runtime.v1.SandboxCheckpointResponse
	(*ListSandboxesRequest)(nil),         // 12: runtime.v1.ListSandboxesRequest
	(*ListSandboxesResponse)(nil),        // 13: runtime.v1.ListSandboxesResponse
	(*SandboxStatus)(nil),                // 14: runtime.v1.SandboxStatus
	(*LinuxSandboxResources)(nil),        // 15: runtime.v1.LinuxSandboxResources
	(*SandboxMetadata)(nil),              // 16: runtime.v1.SandboxMetadata
	(*SandboxMetadataList)(nil),          // 17: runtime.v1.SandboxMetadataList
	nil,                                  // 18: runtime.v1.SandboxStartRequest.EnvsEntry
	nil,                                  // 19: runtime.v1.SandboxStartRequest.ResourcesEntry
	nil,                                  // 20: runtime.v1.SandboxStartRequest.LabelsEntry
	nil,                                  // 21: runtime.v1.SandboxStartRequest.MetricLabelsEntry
	nil,                                  // 22: runtime.v1.SandboxTemplate.EnvsEntry
	nil,                                  // 23: runtime.v1.ListSandboxesRequest.SelectorEntry
	nil,                                  // 24: runtime.v1.SandboxStatus.LabelsEntry
	nil,                                  // 25: runtime.v1.SandboxStatus.MetricLabelsEntry
	nil,                                  // 26: runtime.v1.LinuxSandboxResources.UnifiedEntry
	nil,                                  // 27: runtime.v1.SandboxMetadata.LabelsEntry
	nil,                                  // 28: runtime.v1.SandboxMetadata.MetricLabelsEntry
	nil,                                  // 29: runtime.v1.SandboxMetadataList.SandboxesEntry
	(*RootfsConfig)(nil),                 // 30: runtime.v1.RootfsConfig
	(*Mount)(nil),                        // 31: runtime.v1.Mount
	(*KeyValue)(nil),                     // 32: runtime.v1.KeyValue
	(*HugepageLimit)(nil),                // 33: runtime.v1.HugepageLimit
	(*DeleteRequest)(nil),                // 34: runtime.v1.DeleteRequest
	(*WaitRequest)(nil),                  // 35: runtime.v1.WaitRequest
	(*StatsRequest)(nil),                 // 36: runtime.v1.StatsRequest
	(*StartResponse)(nil),                // 37: runtime.v1.StartResponse
	(*DeleteResponse)(nil),               // 38: runtime.v1.DeleteResponse
	(*WaitResponse)(nil),                 // 39: runtime.v1.WaitResponse
	(*StatsResponse)(nil),                // 40: runtime.v1.StatsResponse
}
var file_sandbox_api_proto_depIdxs = []int32{
	30, // 0: runtime.v1.SandboxStartRequest.rootfs:type_name -> runtime.v1.RootfsConfig
	18, // 1: runtime.v1.SandboxStartRequest.envs:type_name -> runtime.v1.SandboxStartRequest.EnvsEntry
	31, // 2: runtime.v1.SandboxStartRequest.mounts:type_name -> runtime.v1.Mount
	19, // 3: runtime.v1.SandboxStartRequest.resources:type_name -> runtime.v1.SandboxStartRequest.ResourcesEntry
	20, // 4: runtime.v1.SandboxStartRequest.labels:type_name -> runtime.v1.SandboxStartRequest.LabelsEntry
	21, // 5: runtime.v1.SandboxStartRequest.metric_labels:type_name -> runtime.v1.SandboxStartRequest.MetricLabelsEntry
	1,  // 6: runtime.v1.RestoreRequest.sandbox:type_name -> runtime.v1.SandboxStartRequest
	30, // 7: runtime.v1.SandboxTemplate.rootfs:type_name -> runtime.v1.RootfsConfig
	22, // 8: runtime.v1.SandboxTemplate.envs:type_name -> runtime.v1.SandboxTemplate.EnvsEntry
	31, // 9: runtime.v1.SandboxTemplate.mounts:type_name -> runtime.v1.Mount
	4,  // 10: runtime.v1.SandboxRegisterRequest.templates:type_name -> runtime.v1.SandboxTemplate
	4,  // 11: runtime.v1.SandboxGetRegisteredResponse.templates:type_name -> runtime.v1.SandboxTemplate
	23, // 12: runtime.v1.ListSandboxesRequest.selector:type_name -> runtime.v1.ListSandboxesRequest.SelectorEntry
	14, // 13: runtime.v1.ListSandboxesResponse.sandboxes:type_name -> runtime.v1.SandboxStatus
	0,  // 14: runtime.v1.SandboxStatus.state:type_name -> runtime.v1.SandboxState
	24, // 15: runtime.v1.SandboxStatus.labels:type_name -> runtime.v1.SandboxStatus.LabelsEntry
	31, // 16: runtime.v1.SandboxStatus.mounts:type_name -> runtime.v1.Mount
	32, // 17: runtime.v1.SandboxStatus.envs:type_name -> runtime.v1.KeyValue
	15, // 18: runtime.v1.SandboxStatus.resources:type_name -> runtime.v1.LinuxSandboxResources
	25, // 19: runtime.v1.SandboxStatus.metric_labels:type_name -> runtime.v1.SandboxStatus.MetricLabelsEntry
	33, // 20: runtime.v1.LinuxSandboxResources.hugepage_limits:type_name -> runtime.v1.HugepageLimit
	26, // 21: runtime.v1.LinuxSandboxResources.unified:type_name -> runtime.v1.LinuxSandboxResources.UnifiedEntry
	27, // 22: runtime.v1.SandboxMetadata.labels:type_name -> runtime.v1.SandboxMetadata.LabelsEntry
	28, // 23: runtime.v1.SandboxMetadata.metric_labels:type_name -> runtime.v1.SandboxMetadata.MetricLabelsEntry
	29, // 24: runtime.v1.SandboxMetadataList.sandboxes:type_name -> runtime.v1.SandboxMetadataList.SandboxesEntry
	16, // 25: runtime.v1.SandboxMetadataList.SandboxesEntry.value:type_name -> runtime.v1.SandboxMetadata
	1,  // 26: runtime.v1.SandboxService.Start:input_type -> runtime.v1.SandboxStartRequest
	2,  // 27: runtime.v1.SandboxService.Restore:input_type -> runtime.v1.RestoreRequest
	34, // 28: runtime.v1.SandboxService.Delete:input_type -> runtime.v1.DeleteRequest
	35, // 29: runtime.v1.SandboxService.Wait:input_type -> runtime.v1.WaitRequest
	12, // 30: runtime.v1.SandboxService.List:input_type -> runtime.v1.ListSandboxesRequest
	36, // 31: runtime.v1.SandboxService.Stats:input_type -> runtime.v1.StatsRequest
	5,  // 32: runtime.v1.SandboxService.Register:input_type -> runtime.v1.SandboxRegisterRequest
	7,  // 33: runtime.v1.SandboxService.Unregister:input_type -> runtime.v1.SandboxUnregisterRequest
	8,  // 34: runtime.v1.SandboxService.GetRegistered:input_type -> runtime.v1.SandboxGetRegisteredRequest
	10, // 35: runtime.v1.SandboxService.Checkpoint:input_type -> runtime.v1.SandboxCheckpointRequest
	37, // 36: runtime.v1.SandboxService.Start:output_type -> runtime.v1.StartResponse
	3,  // 37: runtime.v1.SandboxService.Restore:output_type -> runtime.v1.RestoreResponse
	38, // 38: runtime.v1.SandboxService.Delete:output_type -> runtime.v1.DeleteResponse
	39, // 39: runtime.v1.SandboxService.Wait:output_type -> runtime.v1.WaitResponse
	13, // 40: runtime.v1.SandboxService.List:output_type -> runtime.v1.ListSandboxesResponse
	40, // 41: runtime.v1.SandboxService.Stats:output_type -> runtime.v1.StatsResponse
	6,  // 42: runtime.v1.SandboxService.Register:output_type -> runtime.v1.SandboxNormalResponse
	6,  // 43: runtime.v1.SandboxService.Unregister:output_type -> runtime.v1.SandboxNormalResponse
	9,  // 44: runtime.v1.SandboxService.GetRegistered:output_type -> runtime.v1.SandboxGetRegisteredResponse
	11, // 45: runtime.v1.SandboxService.Checkpoint:output_type -> runtime.v1.SandboxCheckpointResponse
	36, // [36:46] is the sub-list for method output_type
	26, // [26:36] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_sandbox_api_proto_init() }
func file_sandbox_api_proto_init() {
	if File_sandbox_api_proto != nil {
		return
	}
	file_runtime_launcher_interface_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_api_proto_rawDesc), len(file_sandbox_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_api_proto_goTypes,
		DependencyIndexes: file_sandbox_api_proto_depIdxs,
		EnumInfos:         file_sandbox_api_proto_enumTypes,
		MessageInfos:      file_sandbox_api_proto_msgTypes,
	}.Build()
	File_sandbox_api_proto = out.File
	file_sandbox_api_proto_goTypes = nil
	file_sandbox_api_proto_depIdxs = nil
}
