//! Port of `functionsystem/src/common/status/status.h`.

use std::fmt;

#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StatusCode {
    Failed = -1,
    Success = 0,
    Reserved = 1,
    LogConfigError = 2,
    ParameterError = 3,
    EnvConfigError = 4,
    RequestTimeOut = 5,
    ResourceNotEnough = 6,
    ScheduleConflicted = 7,
    InstanceAllocated = 8,
    FileNotFound = 9,
    JsonParseError = 10,
    RegisterError = 11,
    ConnError = 12,
    PointerIsNull = 13,
    StsDisabled = 14,
    SyncGrpcCallError = 100,
    GrpcCqError = 101,
    GrpcCallObjError = 102,
    GrpcStreamCallError = 103,
    GrpcOk = 104,
    GrpcCancelled = 105,
    GrpcUnknown = 106,
    GrpcInvalidArgument = 107,
    GrpcDeadlineExceeded = 108,
    GrpcNotFound = 109,
    GrpcAlreadyExists = 110,
    GrpcPermissionDenied = 111,
    GrpcResourceExhausted = 112,
    GrpcFailedPrecondition = 113,
    GrpcAborted = 114,
    GrpcOutOfRange = 115,
    GrpcUnimplemented = 116,
    GrpcInternal = 117,
    GrpcUnavailable = 118,
    GrpcDataLoss = 119,
    GrpcUnauthenticated = 120,
    PluginRegisterError = 200,
    PluginUnregisterError = 201,
    FilterPluginError = 202,
    ScorePluginSerror = 203,
    BingPluginError = 204,
    PostBindPluginError = 205,
    InstanceUnscheduleError = 206,
    InvalidResourceParameter = 207,
    AffinityScheduleFailed = 208,
    HeterogeneousScheduleFailed = 209,
    DiskScheduleFailed = 210,
    InstanceTransactionWrongVersion = 300,
    InstanceTransactionGetInfoFailed = 301,
    InstanceTransactionWrongResponseSize = 302,
    InstanceTransactionDeleteFailed = 303,
    InstanceTransactionWrongParameter = 304,
    ErrParamInvalid = 1001,
    ErrResourceNotEnough = 1002,
    ErrInstanceNotFound = 1003,
    ErrInstanceDuplicated = 1004,
    ErrInvokeRateLimited = 1005,
    ErrResourceConfigError = 1006,
    ErrInstanceExited = 1007,
    ErrExtensionMetaError = 1008,
    ErrInstanceSubHealth = 1009,
    ErrGroupScheduleFailed = 1010,
    ErrGroupExitTogether = 1011,
    ErrCreateRateLimited = 1012,
    ErrInstanceEvicted = 1013,
    ErrAuthorizeFailed = 1014,
    ErrFunctionMetaNotFound = 1015,
    ErrInstanceInfoInvalid = 1016,
    ErrScheduleCanceled = 1017,
    ErrSchedulePluginConfig = 1018,
    ErrSubStateInvalid = 1019,
    ErrInstanceSuspend = 1020,
    ErrInstanceBusy = 1021,
    ErrUserCodeLoad = 2001,
    ErrUserFunctionException = 2002,
    ErrRequestBetweenRuntimeBus = 3001,
    ErrInnerCommunication = 3002,
    ErrInnerSystemError = 3003,
    ErrDisconnectFrontendBus = 3004,
    ErrEtcdOperationError = 3005,
    ErrBusDisconnection = 3006,
    ErrRedisOperationError = 3007,
    ErrK8sUnavailable = 3008,
    ErrFunctionAgentOperationError = 3009,
    ErrStateMachineError = 3010,
    ErrLocalSchedulerOperationError = 3011,
    ErrRuntimeManagerOperationError = 3012,
    ErrInstanceManagerOperationError = 3013,
    ErrLocalSchedulerAbnormal = 3014,
    ErrDsUnavailable = 3015,
    ErrNpuFaultError = 3016,
    BpDatasystemError = 10000,
    BpInstanceNotFound = 10001,
    BpMetaStoragePutError = 10002,
    BpMetaStorageDeleteError = 10003,
    BpMetaStorageRevokeError = 10004,
    BpLeaseIdNotFound = 10005,
    BpProxyactorNull = 10006,
    BpMetaStorageGrantError = 10007,
    InstanceHeartbeatLost = 10008,
    InstanceHealthCheckError = 10009,
    InstanceSubHealth = 10010,
    DsScaleDown = 10011,
    FaHttpRegisterHandlerNullError = 20000,
    FaHttpRegisterRepeatUrlError = 20001,
    FaRequiredCpuSizeInvalid = 20002,
    FaRequiredMemorySizeInvalid = 20003,
    FaCpuNotEnough = 20004,
    FaMemoryNotEnough = 20005,
    FaCustomResourceNotEnough = 20006,
    FaFunctionMetaNotExisted = 20007,
    FaFunctionMetaEmptyCpu = 20008,
    FaFunctionMetaEmptyMemory = 20009,
    InstanceFailedOrKilled = 30000,
    RuntimeErrorFatal = 30001,
    RuntimeErrorNonFatal = 30002,
    InstanceDiskUsageExceedLimit = 30003,
    GsGetFromMetastoreFailed = 40000,
    GsPutToMetastoreFailed = 40001,
    GsSchedTopologyBroken = 40002,
    GsActivateDomainFailed = 40003,
    GsRegisterRequestInvalid = 40004,
    GsRegisteredSchedulerTopologyIsNone = 40005,
    GsStartScalerFailed = 40006,
    GsStartCreateDeploymentsFailed = 40007,
    GsStartCreatePodFailed = 40008,
    LsDomainSchedulerAidEmpty = 50000,
    LsGlobalSchedulerAidEmpty = 50001,
    LsInstanceCtrlIsNull = 50002,
    LsRegistryTimeout = 50003,
    LsMetaStoreAccessorIsNull = 50004,
    LsPingPongIsNull = 50005,
    LsSyncRescheduleInstanceFail = 50006,
    LsSyncKillInstanceFail = 50007,
    LsSyncDeployInstanceFail = 50008,
    LsSyncInstanceFail = 50009,
    LsDeployInstanceFailed = 50010,
    LsInitRuntimeFailed = 50011,
    LsAgentMgrStartHeartBeatFail = 50012,
    LsAgentNotFound = 50013,
    LsResourceViewIsNull = 50014,
    LsSyncInstanceComplete = 50015,
    LsMetaStorageGetError = 50016,
    LsRequestNotFound = 50017,
    LsForwardDomainTimeout = 50018,
    LsForwardRequestIsNull = 50019,
    LsUpdateInstanceFail = 50020,
    LsForwardInstanceManagerTimeout = 50021,
    LsAgentEvicted = 50022,
    LsDeployGetTemporaryAccessKeyFail = 50023,
    DomainSchedulerRegisterErr = 60000,
    DomainSchedulerForwardErr = 60001,
    DomainSchedulerUnavailableScheduler = 60002,
    DomainSchedulerReserve = 60003,
    DomainSchedulerNoPreemptableInstance = 60004,
    FuncAgentRequestIdIllegalError = 70050,
    FuncAgentRequestIdRepeatError = 70051,
    FuncAgentInvalidDeployerError = 70052,
    FuncAgentFailedDeploy = 70053,
    FuncAgentDeploymentConfigNotFound = 70054,
    FuncAgentRepeatedDeployRequestError = 70055,
    FuncAgentSetNetworkError = 70056,
    FuncAgentNetworkWorkError = 70057,
    FuncAgentExited = 70058,
    FuncAgentInvalidTokenError = 70059,
    FuncAgentInvalidAccessKeyError = 70060,
    FuncAgentInvalidSecretAccessKeyError = 70061,
    FuncAgentInvalidWorkingDirFile = 70062,
    FuncAgentMkdirDestWorkingDirError = 70063,
    FuncAgentUnsupportedWorkingDirSchema = 70064,
    FuncAgentObsGetObjectError = 70065,
    FuncAgentObsRenameTmpError = 70066,
    FuncAgentObsConnectionError = 70067,
    FuncAgentObsErrorNeedRetry = 70068,
    FuncAgentPingPongIsNull = 70070,
    FuncAgentResourceUnitIsNull = 70071,
    FuncAgentStartHeartbeatFailed = 70072,
    FuncAgentInvalidStorageType = 70073,
    FuncAgentInvalidDeployDirectory = 70074,
    FuncAgentStartRuntimeFailed = 70075,
    FuncAgentStatusVpcProbeFailed = 70076,
    FuncAgentRegisInfoSerializedFailed = 70077,
    FuncAgentCleanCodePackageTimeOut = 70080,
    FuncAgentIllegalNspUrl = 70090,
    FuncAgentNspRequestFailed = 70091,
    FuncAgentNspResponseFailed = 70092,
    FuncAgentIllegalObsUrl = 70093,
    FuncAgentIllegalObsMethod = 70094,
    FuncAgentIllegalObsHeaders = 70095,
    FuncAgentObsRequestFailed = 70096,
    FuncAgentObsResponseFailed = 70097,
    FuncAgentObsIllegalRanges = 70098,
    FuncAgentNspAuthParamsError = 70099,
    RuntimeManagerPortUnavailable = 80000,
    RuntimeManagerExecPathNotFound = 80001,
    RuntimeManagerBuildArgsInvalid = 80002,
    RuntimeManagerMountVolumeFailed = 80003,
    RuntimeManagerCreateExecFailed = 80004,
    RuntimeManagerExecutablePathInvalid = 80005,
    RuntimeManagerRuntimeProcessNotFound = 80006,
    RuntimeManagerExecRunCommandFailed = 80007,
    RuntimeManagerExecStopRunCommandFailed = 80008,
    RuntimeManagerExecDaemonExit = 80009,
    RuntimeManagerStopInstanceFailed = 80010,
    RuntimeManagerExecGetOutputFailed = 80011,
    RuntimeManagerStartInstanceFailed = 80012,
    RuntimeManagerParamsInvalid = 80013,
    RuntimeManagerDiskUsageExceedLimit = 80014,
    RuntimeManagerInstanceHasBeenDeployed = 80015,
    RuntimeManagerPostStartExecFailed = 80016,
    RuntimeManagerCleanStatusResponseTimeOut = 80017,
    RuntimeManagerRegisterFailed = 80018,
    RuntimeManagerUpdateTokenFailed = 80019,
    RuntimeManagerExecWritePipeFailed = 80020,
    RuntimeManagerGpuNotfound = 80021,
    RuntimeManagerGpuPartitionNotfound = 80022,
    RuntimeManagerNpuNotfound = 80023,
    RuntimeManagerNpuPartitionNotfound = 80024,
    RuntimeManagerInstanceExist = 80025,
    RuntimeManagerWorkingDirForAppNotfound = 80026,
    RuntimeManagerDeployDirIsEmpty = 80027,
    RuntimeManagerDebugServerNotfound = 80028,
    RuntimeManagerCondaParamsInvalid = 80029,
    RuntimeManagerCondaEnvFileWriteFailed = 80030,
    RuntimeManagerCondaEnvNotExist = 80031,
    IamWaitInitializeComplete = 90000,
    MetaStoreBackUpErr = 91000,
}

#[allow(non_upper_case_globals)]
impl StatusCode {
    pub const FuncAgentObsInitOptionsError: StatusCode = StatusCode::FuncAgentInvalidAccessKeyError;
    pub const FuncAgentObsOpenFileError: StatusCode = StatusCode::FuncAgentInvalidSecretAccessKeyError;
    pub const FuncAgentObsAddBucketError: StatusCode = StatusCode::FuncAgentInvalidWorkingDirFile;
    pub const FuncAgentObsDelBucketError: StatusCode = StatusCode::FuncAgentMkdirDestWorkingDirError;
    pub const FuncAgentObsPutObjectError: StatusCode = StatusCode::FuncAgentUnsupportedWorkingDirSchema;
}

impl TryFrom<i32> for StatusCode {
    type Error = ();
    fn try_from(value: i32) -> Result<Self, Self::Error> {
        match value {
            -1 => Ok(Self::Failed),
            0 => Ok(Self::Success),
            1 => Ok(Self::Reserved),
            2 => Ok(Self::LogConfigError),
            3 => Ok(Self::ParameterError),
            4 => Ok(Self::EnvConfigError),
            5 => Ok(Self::RequestTimeOut),
            6 => Ok(Self::ResourceNotEnough),
            7 => Ok(Self::ScheduleConflicted),
            8 => Ok(Self::InstanceAllocated),
            9 => Ok(Self::FileNotFound),
            10 => Ok(Self::JsonParseError),
            11 => Ok(Self::RegisterError),
            12 => Ok(Self::ConnError),
            13 => Ok(Self::PointerIsNull),
            14 => Ok(Self::StsDisabled),
            100 => Ok(Self::SyncGrpcCallError),
            101 => Ok(Self::GrpcCqError),
            102 => Ok(Self::GrpcCallObjError),
            103 => Ok(Self::GrpcStreamCallError),
            104 => Ok(Self::GrpcOk),
            105 => Ok(Self::GrpcCancelled),
            106 => Ok(Self::GrpcUnknown),
            107 => Ok(Self::GrpcInvalidArgument),
            108 => Ok(Self::GrpcDeadlineExceeded),
            109 => Ok(Self::GrpcNotFound),
            110 => Ok(Self::GrpcAlreadyExists),
            111 => Ok(Self::GrpcPermissionDenied),
            112 => Ok(Self::GrpcResourceExhausted),
            113 => Ok(Self::GrpcFailedPrecondition),
            114 => Ok(Self::GrpcAborted),
            115 => Ok(Self::GrpcOutOfRange),
            116 => Ok(Self::GrpcUnimplemented),
            117 => Ok(Self::GrpcInternal),
            118 => Ok(Self::GrpcUnavailable),
            119 => Ok(Self::GrpcDataLoss),
            120 => Ok(Self::GrpcUnauthenticated),
            200 => Ok(Self::PluginRegisterError),
            201 => Ok(Self::PluginUnregisterError),
            202 => Ok(Self::FilterPluginError),
            203 => Ok(Self::ScorePluginSerror),
            204 => Ok(Self::BingPluginError),
            205 => Ok(Self::PostBindPluginError),
            206 => Ok(Self::InstanceUnscheduleError),
            207 => Ok(Self::InvalidResourceParameter),
            208 => Ok(Self::AffinityScheduleFailed),
            209 => Ok(Self::HeterogeneousScheduleFailed),
            210 => Ok(Self::DiskScheduleFailed),
            300 => Ok(Self::InstanceTransactionWrongVersion),
            301 => Ok(Self::InstanceTransactionGetInfoFailed),
            302 => Ok(Self::InstanceTransactionWrongResponseSize),
            303 => Ok(Self::InstanceTransactionDeleteFailed),
            304 => Ok(Self::InstanceTransactionWrongParameter),
            1001 => Ok(Self::ErrParamInvalid),
            1002 => Ok(Self::ErrResourceNotEnough),
            1003 => Ok(Self::ErrInstanceNotFound),
            1004 => Ok(Self::ErrInstanceDuplicated),
            1005 => Ok(Self::ErrInvokeRateLimited),
            1006 => Ok(Self::ErrResourceConfigError),
            1007 => Ok(Self::ErrInstanceExited),
            1008 => Ok(Self::ErrExtensionMetaError),
            1009 => Ok(Self::ErrInstanceSubHealth),
            1010 => Ok(Self::ErrGroupScheduleFailed),
            1011 => Ok(Self::ErrGroupExitTogether),
            1012 => Ok(Self::ErrCreateRateLimited),
            1013 => Ok(Self::ErrInstanceEvicted),
            1014 => Ok(Self::ErrAuthorizeFailed),
            1015 => Ok(Self::ErrFunctionMetaNotFound),
            1016 => Ok(Self::ErrInstanceInfoInvalid),
            1017 => Ok(Self::ErrScheduleCanceled),
            1018 => Ok(Self::ErrSchedulePluginConfig),
            1019 => Ok(Self::ErrSubStateInvalid),
            1020 => Ok(Self::ErrInstanceSuspend),
            1021 => Ok(Self::ErrInstanceBusy),
            2001 => Ok(Self::ErrUserCodeLoad),
            2002 => Ok(Self::ErrUserFunctionException),
            3001 => Ok(Self::ErrRequestBetweenRuntimeBus),
            3002 => Ok(Self::ErrInnerCommunication),
            3003 => Ok(Self::ErrInnerSystemError),
            3004 => Ok(Self::ErrDisconnectFrontendBus),
            3005 => Ok(Self::ErrEtcdOperationError),
            3006 => Ok(Self::ErrBusDisconnection),
            3007 => Ok(Self::ErrRedisOperationError),
            3008 => Ok(Self::ErrK8sUnavailable),
            3009 => Ok(Self::ErrFunctionAgentOperationError),
            3010 => Ok(Self::ErrStateMachineError),
            3011 => Ok(Self::ErrLocalSchedulerOperationError),
            3012 => Ok(Self::ErrRuntimeManagerOperationError),
            3013 => Ok(Self::ErrInstanceManagerOperationError),
            3014 => Ok(Self::ErrLocalSchedulerAbnormal),
            3015 => Ok(Self::ErrDsUnavailable),
            3016 => Ok(Self::ErrNpuFaultError),
            10000 => Ok(Self::BpDatasystemError),
            10001 => Ok(Self::BpInstanceNotFound),
            10002 => Ok(Self::BpMetaStoragePutError),
            10003 => Ok(Self::BpMetaStorageDeleteError),
            10004 => Ok(Self::BpMetaStorageRevokeError),
            10005 => Ok(Self::BpLeaseIdNotFound),
            10006 => Ok(Self::BpProxyactorNull),
            10007 => Ok(Self::BpMetaStorageGrantError),
            10008 => Ok(Self::InstanceHeartbeatLost),
            10009 => Ok(Self::InstanceHealthCheckError),
            10010 => Ok(Self::InstanceSubHealth),
            10011 => Ok(Self::DsScaleDown),
            20000 => Ok(Self::FaHttpRegisterHandlerNullError),
            20001 => Ok(Self::FaHttpRegisterRepeatUrlError),
            20002 => Ok(Self::FaRequiredCpuSizeInvalid),
            20003 => Ok(Self::FaRequiredMemorySizeInvalid),
            20004 => Ok(Self::FaCpuNotEnough),
            20005 => Ok(Self::FaMemoryNotEnough),
            20006 => Ok(Self::FaCustomResourceNotEnough),
            20007 => Ok(Self::FaFunctionMetaNotExisted),
            20008 => Ok(Self::FaFunctionMetaEmptyCpu),
            20009 => Ok(Self::FaFunctionMetaEmptyMemory),
            30000 => Ok(Self::InstanceFailedOrKilled),
            30001 => Ok(Self::RuntimeErrorFatal),
            30002 => Ok(Self::RuntimeErrorNonFatal),
            30003 => Ok(Self::InstanceDiskUsageExceedLimit),
            40000 => Ok(Self::GsGetFromMetastoreFailed),
            40001 => Ok(Self::GsPutToMetastoreFailed),
            40002 => Ok(Self::GsSchedTopologyBroken),
            40003 => Ok(Self::GsActivateDomainFailed),
            40004 => Ok(Self::GsRegisterRequestInvalid),
            40005 => Ok(Self::GsRegisteredSchedulerTopologyIsNone),
            40006 => Ok(Self::GsStartScalerFailed),
            40007 => Ok(Self::GsStartCreateDeploymentsFailed),
            40008 => Ok(Self::GsStartCreatePodFailed),
            50000 => Ok(Self::LsDomainSchedulerAidEmpty),
            50001 => Ok(Self::LsGlobalSchedulerAidEmpty),
            50002 => Ok(Self::LsInstanceCtrlIsNull),
            50003 => Ok(Self::LsRegistryTimeout),
            50004 => Ok(Self::LsMetaStoreAccessorIsNull),
            50005 => Ok(Self::LsPingPongIsNull),
            50006 => Ok(Self::LsSyncRescheduleInstanceFail),
            50007 => Ok(Self::LsSyncKillInstanceFail),
            50008 => Ok(Self::LsSyncDeployInstanceFail),
            50009 => Ok(Self::LsSyncInstanceFail),
            50010 => Ok(Self::LsDeployInstanceFailed),
            50011 => Ok(Self::LsInitRuntimeFailed),
            50012 => Ok(Self::LsAgentMgrStartHeartBeatFail),
            50013 => Ok(Self::LsAgentNotFound),
            50014 => Ok(Self::LsResourceViewIsNull),
            50015 => Ok(Self::LsSyncInstanceComplete),
            50016 => Ok(Self::LsMetaStorageGetError),
            50017 => Ok(Self::LsRequestNotFound),
            50018 => Ok(Self::LsForwardDomainTimeout),
            50019 => Ok(Self::LsForwardRequestIsNull),
            50020 => Ok(Self::LsUpdateInstanceFail),
            50021 => Ok(Self::LsForwardInstanceManagerTimeout),
            50022 => Ok(Self::LsAgentEvicted),
            50023 => Ok(Self::LsDeployGetTemporaryAccessKeyFail),
            60000 => Ok(Self::DomainSchedulerRegisterErr),
            60001 => Ok(Self::DomainSchedulerForwardErr),
            60002 => Ok(Self::DomainSchedulerUnavailableScheduler),
            60003 => Ok(Self::DomainSchedulerReserve),
            60004 => Ok(Self::DomainSchedulerNoPreemptableInstance),
            70050 => Ok(Self::FuncAgentRequestIdIllegalError),
            70051 => Ok(Self::FuncAgentRequestIdRepeatError),
            70052 => Ok(Self::FuncAgentInvalidDeployerError),
            70053 => Ok(Self::FuncAgentFailedDeploy),
            70054 => Ok(Self::FuncAgentDeploymentConfigNotFound),
            70055 => Ok(Self::FuncAgentRepeatedDeployRequestError),
            70056 => Ok(Self::FuncAgentSetNetworkError),
            70057 => Ok(Self::FuncAgentNetworkWorkError),
            70058 => Ok(Self::FuncAgentExited),
            70059 => Ok(Self::FuncAgentInvalidTokenError),
            70060 => Ok(Self::FuncAgentInvalidAccessKeyError),
            70061 => Ok(Self::FuncAgentInvalidSecretAccessKeyError),
            70062 => Ok(Self::FuncAgentInvalidWorkingDirFile),
            70063 => Ok(Self::FuncAgentMkdirDestWorkingDirError),
            70064 => Ok(Self::FuncAgentUnsupportedWorkingDirSchema),
            70065 => Ok(Self::FuncAgentObsGetObjectError),
            70066 => Ok(Self::FuncAgentObsRenameTmpError),
            70067 => Ok(Self::FuncAgentObsConnectionError),
            70068 => Ok(Self::FuncAgentObsErrorNeedRetry),
            70070 => Ok(Self::FuncAgentPingPongIsNull),
            70071 => Ok(Self::FuncAgentResourceUnitIsNull),
            70072 => Ok(Self::FuncAgentStartHeartbeatFailed),
            70073 => Ok(Self::FuncAgentInvalidStorageType),
            70074 => Ok(Self::FuncAgentInvalidDeployDirectory),
            70075 => Ok(Self::FuncAgentStartRuntimeFailed),
            70076 => Ok(Self::FuncAgentStatusVpcProbeFailed),
            70077 => Ok(Self::FuncAgentRegisInfoSerializedFailed),
            70080 => Ok(Self::FuncAgentCleanCodePackageTimeOut),
            70090 => Ok(Self::FuncAgentIllegalNspUrl),
            70091 => Ok(Self::FuncAgentNspRequestFailed),
            70092 => Ok(Self::FuncAgentNspResponseFailed),
            70093 => Ok(Self::FuncAgentIllegalObsUrl),
            70094 => Ok(Self::FuncAgentIllegalObsMethod),
            70095 => Ok(Self::FuncAgentIllegalObsHeaders),
            70096 => Ok(Self::FuncAgentObsRequestFailed),
            70097 => Ok(Self::FuncAgentObsResponseFailed),
            70098 => Ok(Self::FuncAgentObsIllegalRanges),
            70099 => Ok(Self::FuncAgentNspAuthParamsError),
            80000 => Ok(Self::RuntimeManagerPortUnavailable),
            80001 => Ok(Self::RuntimeManagerExecPathNotFound),
            80002 => Ok(Self::RuntimeManagerBuildArgsInvalid),
            80003 => Ok(Self::RuntimeManagerMountVolumeFailed),
            80004 => Ok(Self::RuntimeManagerCreateExecFailed),
            80005 => Ok(Self::RuntimeManagerExecutablePathInvalid),
            80006 => Ok(Self::RuntimeManagerRuntimeProcessNotFound),
            80007 => Ok(Self::RuntimeManagerExecRunCommandFailed),
            80008 => Ok(Self::RuntimeManagerExecStopRunCommandFailed),
            80009 => Ok(Self::RuntimeManagerExecDaemonExit),
            80010 => Ok(Self::RuntimeManagerStopInstanceFailed),
            80011 => Ok(Self::RuntimeManagerExecGetOutputFailed),
            80012 => Ok(Self::RuntimeManagerStartInstanceFailed),
            80013 => Ok(Self::RuntimeManagerParamsInvalid),
            80014 => Ok(Self::RuntimeManagerDiskUsageExceedLimit),
            80015 => Ok(Self::RuntimeManagerInstanceHasBeenDeployed),
            80016 => Ok(Self::RuntimeManagerPostStartExecFailed),
            80017 => Ok(Self::RuntimeManagerCleanStatusResponseTimeOut),
            80018 => Ok(Self::RuntimeManagerRegisterFailed),
            80019 => Ok(Self::RuntimeManagerUpdateTokenFailed),
            80020 => Ok(Self::RuntimeManagerExecWritePipeFailed),
            80021 => Ok(Self::RuntimeManagerGpuNotfound),
            80022 => Ok(Self::RuntimeManagerGpuPartitionNotfound),
            80023 => Ok(Self::RuntimeManagerNpuNotfound),
            80024 => Ok(Self::RuntimeManagerNpuPartitionNotfound),
            80025 => Ok(Self::RuntimeManagerInstanceExist),
            80026 => Ok(Self::RuntimeManagerWorkingDirForAppNotfound),
            80027 => Ok(Self::RuntimeManagerDeployDirIsEmpty),
            80028 => Ok(Self::RuntimeManagerDebugServerNotfound),
            80029 => Ok(Self::RuntimeManagerCondaParamsInvalid),
            80030 => Ok(Self::RuntimeManagerCondaEnvFileWriteFailed),
            80031 => Ok(Self::RuntimeManagerCondaEnvNotExist),
            90000 => Ok(Self::IamWaitInitializeComplete),
            91000 => Ok(Self::MetaStoreBackUpErr),
            _ => Err(()),
        }
    }
}

impl From<StatusCode> for i32 {
    fn from(c: StatusCode) -> i32 {
        c as i32
    }
}

/// Application-level status aligned with C++ `functionsystem::Status`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Status {
    pub code: StatusCode,
    pub message: String,
    pub data: Option<String>,
}

impl Status {
    pub fn ok() -> Self {
        Self {
            code: StatusCode::Success,
            message: String::new(),
            data: None,
        }
    }

    pub fn new(code: StatusCode, message: impl Into<String>) -> Self {
        Self {
            code,
            message: message.into(),
            data: None,
        }
    }

    pub fn with_data(mut self, data: impl Into<String>) -> Self {
        self.data = Some(data.into());
        self
    }

    pub fn is_ok(&self) -> bool {
        self.code == StatusCode::Success
    }

    pub fn is_error(&self) -> bool {
        !self.is_ok()
    }
}

impl fmt::Display for Status {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "Status({:?} [{}]): {}",
            self.code,
            i32::from(self.code),
            self.message
        )?;
        if let Some(d) = &self.data {
            write!(f, " data={d}")?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn status_ok_and_error() {
        assert!(Status::ok().is_ok());
        let e = Status::new(StatusCode::Failed, "x");
        assert!(e.is_error());
    }

    #[test]
    fn status_code_roundtrip() {
        let c = StatusCode::ErrStateMachineError;
        let v: i32 = c.into();
        assert_eq!(StatusCode::try_from(v).unwrap(), c);
    }

    #[test]
    fn status_code_duplicate_numeric_aliases() {
        assert_eq!(
            StatusCode::FuncAgentObsInitOptionsError as i32,
            StatusCode::FuncAgentInvalidAccessKeyError as i32
        );
    }
}
